"""
台股 2.1 產業估值分類表（第 17-B-2 全產業校準同步版）。

用途：
- 定義各產業主要估值模型、P/E 或 P/B 適用性、循環股警示與風險旗標。
- 已同步 Dynamic Cap 2.0 全產業校準建議：P/E/P/B 分離、hard ceiling、相對毛利基準、事件模型切換。
"""

INDUSTRY_TAXONOMY = {'FOUNDRY': {'display_name': '晶圓代工 / HPC / 先進製程',
             'parent': '半導體核心',
             'primary_valuation': 'forward_pe',
             'secondary_valuation': ['pb', 'roe', 'gross_margin', 'capex_cycle'],
             'valuation_focus': ['Forward P/E', 'P/B', 'ROE', '毛利率', '產能利用率', '資本支出'],
             'base_pe': 24,
             'pe_range': (20, 35),
             'base_pb': None,
             'pb_range': None,
             'cyclical': True,
             'pe_applicable': True,
             'pe_trap_warning': False,
             'theme_premium_allowed': True,
             'liquidity_sensitive': False,
             'operable_discount_factor': 0.96,
             'risk_flags': ['景氣循環', '資本支出高峰', '毛利率下滑', '先進製程競爭', '匯率'],
             'note': '可使用 P/E/Forward P/E，但需搭配 P/B、ROE 與毛利率交叉驗證。',
             'floor_pe': 18,
             'soft_ceiling_pe': 30,
             'hard_ceiling_pe': 35,
             'max_growth_factor': 1.14,
             'max_quality_factor': 1.1,
             'max_theme_factor': 1.05,
             'max_scale_factor': 1.0,
             'gross_margin_baseline': 0.54,
             'gross_margin_good': 0.58,
             'gross_margin_excellent': 0.62,
             'baked_in_themes': ['AI', 'HPC', 'CoWoS', '先進製程'],
             'geopolitical_factor': 0.92,
             'geopolitical_note': '台灣關鍵半導體供應鏈地緣政治風險折價',
             'calibration_source': '17-B-2 全產業校準表'},
 'IC_DESIGN_ASIC': {'display_name': 'IC 設計 / ASIC / AI 晶片',
                    'parent': '半導體核心',
                    'primary_valuation': 'forward_pe',
                    'secondary_valuation': ['eps_cagr', 'gross_margin', 'roe', 'revenue_growth'],
                    'valuation_focus': ['Forward P/E', 'EPS CAGR', '毛利率', 'ROE', 'AI ASIC 訂單'],
                    'base_pe': 35,
                    'pe_range': (28, 70),
                    'base_pb': None,
                    'pb_range': None,
                    'cyclical': False,
                    'pe_applicable': True,
                    'pe_trap_warning': False,
                    'theme_premium_allowed': True,
                    'liquidity_sensitive': True,
                    'operable_discount_factor': 0.9,
                    'risk_flags': ['客戶集中', 'AI 訂單未確認', '高基期', '毛利率下滑', '庫存修正'],
                    'note': '高毛利與 ASIC 題材可給較高倍率，但需確認 EPS 是否真的上修。',
                    'floor_pe': 22,
                    'soft_ceiling_pe': 55,
                    'hard_ceiling_pe': 70,
                    'max_growth_factor': 1.25,
                    'max_quality_factor': 1.22,
                    'max_theme_factor': 1.18,
                    'max_scale_factor': 1.08,
                    'gross_margin_baseline': 0.42,
                    'gross_margin_good': 0.48,
                    'gross_margin_excellent': 0.55,
                    'baked_in_themes': ['ASIC', 'AI ASIC', 'AI晶片'],
                    'geopolitical_factor': 0.97,
                    'calibration_source': '17-B-2 全產業校準表'},
 'IP_EDA_DESIGN_SERVICE': {'display_name': 'IP / EDA / 設計服務 / 矽智財',
                           'parent': '半導體核心',
                           'primary_valuation': 'forward_pe',
                           'secondary_valuation': ['gross_margin', 'recurring_revenue', 'roe'],
                           'valuation_focus': ['Forward P/E', '毛利率', '授權收入', 'ROE', '設計案能見度'],
                           'base_pe': 42,
                           'pe_range': (32, 80),
                           'base_pb': None,
                           'pb_range': None,
                           'cyclical': False,
                           'pe_applicable': True,
                           'pe_trap_warning': False,
                           'theme_premium_allowed': True,
                           'liquidity_sensitive': True,
                           'operable_discount_factor': 0.88,
                           'risk_flags': ['授權收入波動', '設計案延後', '客戶集中', '估值過高'],
                           'note': '高毛利 IP/EDA 類可給高估值，但需以營收落地與現金流驗證。',
                           'floor_pe': 25,
                           'soft_ceiling_pe': 65,
                           'hard_ceiling_pe': 80,
                           'max_growth_factor': 1.25,
                           'max_quality_factor': 1.25,
                           'max_theme_factor': 1.15,
                           'max_scale_factor': 1.08,
                           'gross_margin_baseline': 0.55,
                           'gross_margin_good': 0.65,
                           'gross_margin_excellent': 0.75,
                           'baked_in_themes': ['IP', 'EDA', '矽智財'],
                           'geopolitical_factor': 0.97,
                           'calibration_source': '17-B-2 全產業校準表'},
 'OSAT_TESTING': {'display_name': '封測 / 測試 / 先進封裝服務',
                  'parent': '半導體核心',
                  'primary_valuation': 'forward_pe',
                  'secondary_valuation': ['utilization', 'capex_cycle', 'gross_margin', 'pb'],
                  'valuation_focus': ['Forward P/E', '稼動率', '先進封裝占比', '毛利率', '資本支出'],
                  'base_pe': 24,
                  'pe_range': (16, 42),
                  'base_pb': None,
                  'pb_range': None,
                  'cyclical': True,
                  'pe_applicable': True,
                  'pe_trap_warning': False,
                  'theme_premium_allowed': True,
                  'liquidity_sensitive': False,
                  'operable_discount_factor': 0.94,
                  'risk_flags': ['稼動率下降', '資本支出高峰', '庫存修正', '價格競爭'],
                  'note': '封測有循環性，先進封裝比重提高時可提升估值。',
                  'floor_pe': 15,
                  'soft_ceiling_pe': 35,
                  'hard_ceiling_pe': 42,
                  'max_growth_factor': 1.18,
                  'max_quality_factor': 1.12,
                  'max_theme_factor': 1.1,
                  'max_scale_factor': 1.04,
                  'gross_margin_baseline': 0.22,
                  'gross_margin_good': 0.28,
                  'gross_margin_excellent': 0.35,
                  'baked_in_themes': ['先進封裝', 'CoWoS'],
                  'geopolitical_factor': 0.96,
                  'calibration_source': '17-B-2 全產業校準表'},
 'PROBE_TEST_INTERFACE': {'display_name': '探針卡 / 測試介面 / 半導體檢測',
                          'parent': '半導體設備與耗材',
                          'primary_valuation': 'forward_pe',
                          'secondary_valuation': ['gross_margin', 'orders', 'revenue_growth', 'fcf'],
                          'valuation_focus': ['Forward P/E', '毛利率', '訂單能見度', '客戶導入', 'FCF'],
                          'base_pe': 32,
                          'pe_range': (24, 55),
                          'base_pb': None,
                          'pb_range': None,
                          'cyclical': False,
                          'pe_applicable': True,
                          'pe_trap_warning': False,
                          'theme_premium_allowed': True,
                          'liquidity_sensitive': True,
                          'operable_discount_factor': 0.9,
                          'risk_flags': ['訂單遞延', '客戶驗證不確定', 'EPS 預估分歧', '高估值修正'],
                          'note': '高毛利檢測介面可給成長溢價，但需看導入時程。',
                          'floor_pe': 20,
                          'soft_ceiling_pe': 45,
                          'hard_ceiling_pe': 55,
                          'max_growth_factor': 1.2,
                          'max_quality_factor': 1.18,
                          'max_theme_factor': 1.1,
                          'max_scale_factor': 1.06,
                          'gross_margin_baseline': 0.38,
                          'gross_margin_good': 0.45,
                          'gross_margin_excellent': 0.52,
                          'baked_in_themes': ['測試', '探針'],
                          'geopolitical_factor': 0.97,
                          'calibration_source': '17-B-2 全產業校準表'},
 'SEMICAP_COWOS_EQUIPMENT': {'display_name': 'CoWoS / 先進封裝 / 半導體設備',
                             'parent': '半導體設備與耗材',
                             'primary_valuation': 'forward_pe',
                             'secondary_valuation': ['orders', 'gross_margin', 'fcf', 'revenue_growth'],
                             'valuation_focus': ['Forward P/E', '訂單能見度', '毛利率', 'FCF', '交期'],
                             'base_pe': 32,
                             'pe_range': (22, 58),
                             'base_pb': None,
                             'pb_range': None,
                             'cyclical': False,
                             'pe_applicable': True,
                             'pe_trap_warning': False,
                             'theme_premium_allowed': True,
                             'liquidity_sensitive': True,
                             'operable_discount_factor': 0.88,
                             'risk_flags': ['認列時程', '客戶驗證', '單月營收轉弱', '法人下修', '高估值'],
                             'note': 'CoWoS 設備可享 AI 題材溢價，但需要訂單與 EPS 同步驗證。',
                             'floor_pe': 20,
                             'soft_ceiling_pe': 48,
                             'hard_ceiling_pe': 58,
                             'max_growth_factor': 1.22,
                             'max_quality_factor': 1.18,
                             'max_theme_factor': 1.12,
                             'max_scale_factor': 1.08,
                             'gross_margin_baseline': 0.3,
                             'gross_margin_good': 0.38,
                             'gross_margin_excellent': 0.45,
                             'baked_in_themes': ['CoWoS', '先進封裝', '設備'],
                             'geopolitical_factor': 0.96,
                             'calibration_source': '17-B-2 全產業校準表'},
 'FAB_FACILITY_MATERIALS': {'display_name': '半導體廠務 / 材料 / 製程耗材',
                            'parent': '半導體設備與耗材',
                            'primary_valuation': 'pe_fcf',
                            'secondary_valuation': ['orders', 'gross_margin', 'pb', 'capex_cycle'],
                            'valuation_focus': ['P/E', '訂單', 'FCF', '毛利率', '晶圓廠資本支出'],
                            'base_pe': 24,
                            'pe_range': (16, 42),
                            'base_pb': None,
                            'pb_range': None,
                            'cyclical': True,
                            'pe_applicable': True,
                            'pe_trap_warning': False,
                            'theme_premium_allowed': True,
                            'liquidity_sensitive': True,
                            'operable_discount_factor': 0.92,
                            'risk_flags': ['資本支出循環', '專案認列', '毛利率波動', '現金流遞延'],
                            'note': '廠務與耗材需看訂單、現金流與台積電/美國建廠週期。',
                            'floor_pe': 14,
                            'soft_ceiling_pe': 36,
                            'hard_ceiling_pe': 42,
                            'max_growth_factor': 1.14,
                            'max_quality_factor': 1.1,
                            'max_theme_factor': 1.06,
                            'max_scale_factor': 1.04,
                            'gross_margin_baseline': 0.24,
                            'gross_margin_good': 0.3,
                            'gross_margin_excellent': 0.36,
                            'baked_in_themes': ['廠務', '材料'],
                            'geopolitical_factor': 0.96,
                            'calibration_source': '17-B-2 全產業校準表'},
 'ABF_SUBSTRATE': {'display_name': 'PCB / ABF / 高階載板',
                   'parent': 'PCB / 載板',
                   'primary_valuation': 'forward_pe',
                   'secondary_valuation': ['pb', 'revenue_growth', 'gross_margin', 'pricing_cycle'],
                   'valuation_focus': ['Forward P/E', 'P/B', '月營收', '毛利率', 'ABF 報價循環'],
                   'base_pe': 30,
                   'pe_range': (22, 55),
                   'base_pb': None,
                   'pb_range': None,
                   'cyclical': True,
                   'pe_applicable': True,
                   'pe_trap_warning': False,
                   'theme_premium_allowed': True,
                   'liquidity_sensitive': True,
                   'operable_discount_factor': 0.9,
                   'risk_flags': ['ABF 報價轉弱', '單月營收衰退', 'EPS 預估分歧', '庫存調整'],
                   'note': '載板不宜只看 TTM P/E；需看 Forward EPS 與報價循環。',
                   'floor_pe': 18,
                   'soft_ceiling_pe': 42,
                   'hard_ceiling_pe': 55,
                   'max_growth_factor': 1.18,
                   'max_quality_factor': 1.14,
                   'max_theme_factor': 1.08,
                   'max_scale_factor': 1.05,
                   'gross_margin_baseline': 0.23,
                   'gross_margin_good': 0.3,
                   'gross_margin_excellent': 0.38,
                   'baked_in_themes': ['ABF', 'AI載板', 'HPC', '載板'],
                   'cyclical_low_base_cap': True,
                   'calibration_source': '17-B-2 全產業校準表'},
 'SERVER_PCB_BOARD': {'display_name': 'AI 伺服器主板 / 高階 PCB',
                      'parent': 'PCB / 載板',
                      'primary_valuation': 'forward_pe',
                      'secondary_valuation': ['revenue_growth', 'gross_margin', 'server_mix'],
                      'valuation_focus': ['Forward P/E', '營收 YoY', '毛利率', '伺服器占比', '客戶訂單'],
                      'base_pe': 28,
                      'pe_range': (18, 50),
                      'base_pb': None,
                      'pb_range': None,
                      'cyclical': True,
                      'pe_applicable': True,
                      'pe_trap_warning': False,
                      'theme_premium_allowed': True,
                      'liquidity_sensitive': True,
                      'operable_discount_factor': 0.9,
                      'risk_flags': ['AI 出貨高峰', '客戶集中', '單月營收轉弱', '毛利率下滑'],
                      'note': '高階 PCB 需分清一般板與 AI 伺服器高階板。',
                      'floor_pe': 16,
                      'soft_ceiling_pe': 40,
                      'hard_ceiling_pe': 50,
                      'max_growth_factor': 1.16,
                      'max_quality_factor': 1.12,
                      'max_theme_factor': 1.08,
                      'max_scale_factor': 1.05,
                      'gross_margin_baseline': 0.18,
                      'gross_margin_good': 0.24,
                      'gross_margin_excellent': 0.3,
                      'baked_in_themes': ['AI伺服器', '高階PCB'],
                      'calibration_source': '17-B-2 全產業校準表'},
 'AI_SERVER_ODM': {'display_name': 'AI 伺服器 ODM / 組裝',
                   'parent': 'AI 伺服器與資料中心',
                   'primary_valuation': 'forward_pe',
                   'secondary_valuation': ['revenue_growth', 'gross_margin', 'inventory', 'customer_orders'],
                   'valuation_focus': ['Forward P/E', '營收動能', '毛利率', 'AI 伺服器占比', '客戶訂單'],
                   'base_pe': 24,
                   'pe_range': (16, 42),
                   'base_pb': None,
                   'pb_range': None,
                   'cyclical': False,
                   'pe_applicable': True,
                   'pe_trap_warning': False,
                   'theme_premium_allowed': True,
                   'liquidity_sensitive': False,
                   'operable_discount_factor': 0.92,
                   'risk_flags': ['低毛利', '客戶砍單', '高基期', '匯率', '出貨高峰後衰退'],
                   'note': 'ODM 出貨量大但毛利低，題材溢價需受毛利率約束。',
                   'floor_pe': 14,
                   'soft_ceiling_pe': 34,
                   'hard_ceiling_pe': 42,
                   'max_growth_factor': 1.16,
                   'max_quality_factor': 1.15,
                   'max_theme_factor': 1.08,
                   'max_scale_factor': 1.03,
                   'gross_margin_baseline': 0.06,
                   'gross_margin_good': 0.09,
                   'gross_margin_excellent': 0.12,
                   'baked_in_themes': ['AI', 'AI伺服器', '資料中心'],
                   'calibration_source': '17-B-2 全產業校準表'},
 'CONNECTOR_CABLE': {'display_name': '高速連接器 / 線材 / 高速傳輸',
                     'parent': 'AI 伺服器與資料中心',
                     'primary_valuation': 'forward_pe',
                     'secondary_valuation': ['gross_margin', 'spec_upgrade', 'customer_validation'],
                     'valuation_focus': ['Forward P/E', '毛利率', '規格升級', '高速傳輸', '客戶認證'],
                     'base_pe': 28,
                     'pe_range': (18, 50),
                     'base_pb': None,
                     'pb_range': None,
                     'cyclical': False,
                     'pe_applicable': True,
                     'pe_trap_warning': False,
                     'theme_premium_allowed': True,
                     'liquidity_sensitive': True,
                     'operable_discount_factor': 0.9,
                     'risk_flags': ['規格轉換', '客戶認證延遲', '產品組合變化', '毛利率下滑'],
                     'note': '高速傳輸與車用認證可提高估值穩定度。',
                     'floor_pe': 16,
                     'soft_ceiling_pe': 42,
                     'hard_ceiling_pe': 50,
                     'max_growth_factor': 1.16,
                     'max_quality_factor': 1.14,
                     'max_theme_factor': 1.08,
                     'max_scale_factor': 1.05,
                     'gross_margin_baseline': 0.25,
                     'gross_margin_good': 0.32,
                     'gross_margin_excellent': 0.4,
                     'baked_in_themes': ['高速傳輸', '連接器'],
                     'calibration_source': '17-B-2 全產業校準表'},
 'SERVER_CHASSIS_RAIL': {'display_name': '機殼 / 滑軌 / 機構件',
                         'parent': 'AI 伺服器與資料中心',
                         'primary_valuation': 'forward_pe',
                         'secondary_valuation': ['orders', 'gross_margin', 'revenue_growth'],
                         'valuation_focus': ['Forward P/E', '訂單', '毛利率', '伺服器機構件占比'],
                         'base_pe': 24,
                         'pe_range': (16, 42),
                         'base_pb': None,
                         'pb_range': None,
                         'cyclical': False,
                         'pe_applicable': True,
                         'pe_trap_warning': False,
                         'theme_premium_allowed': True,
                         'liquidity_sensitive': True,
                         'operable_discount_factor': 0.91,
                         'risk_flags': ['訂單遞延', '價格競爭', '毛利率下滑', '客戶集中'],
                         'note': '機構件需看 AI 機櫃占比與出貨能見度。',
                         'floor_pe': 14,
                         'soft_ceiling_pe': 34,
                         'hard_ceiling_pe': 42,
                         'max_growth_factor': 1.12,
                         'max_quality_factor': 1.1,
                         'max_theme_factor': 1.06,
                         'max_scale_factor': 1.04,
                         'gross_margin_baseline': 0.2,
                         'gross_margin_good': 0.26,
                         'gross_margin_excellent': 0.32,
                         'baked_in_themes': ['機構件', '滑軌', '機殼'],
                         'calibration_source': '17-B-2 全產業校準表'},
 'POWER_BBU': {'display_name': '電源供應 / BBU / 電源模組',
               'parent': 'AI 伺服器與資料中心',
               'primary_valuation': 'forward_pe',
               'secondary_valuation': ['gross_margin', 'server_mix', 'revenue_growth'],
               'valuation_focus': ['Forward P/E', '毛利率', 'BBU/高瓦數 PSU', 'AI 伺服器占比'],
               'base_pe': 24,
               'pe_range': (16, 44),
               'base_pb': None,
               'pb_range': None,
               'cyclical': False,
               'pe_applicable': True,
               'pe_trap_warning': False,
               'theme_premium_allowed': True,
               'liquidity_sensitive': True,
               'operable_discount_factor': 0.92,
               'risk_flags': ['出貨時程', '毛利率變化', '客戶集中', '價格競爭'],
               'note': '高瓦數 PSU/BBU 可享 AI 溢價，但不能與低毛利產品混算。',
               'floor_pe': 14,
               'soft_ceiling_pe': 36,
               'hard_ceiling_pe': 44,
               'max_growth_factor': 1.14,
               'max_quality_factor': 1.1,
               'max_theme_factor': 1.06,
               'max_scale_factor': 1.04,
               'gross_margin_baseline': 0.18,
               'gross_margin_good': 0.24,
               'gross_margin_excellent': 0.3,
               'baked_in_themes': ['電源', 'BBU'],
               'calibration_source': '17-B-2 全產業校準表'},
 'THERMAL_LIQUID_COOLING': {'display_name': '散熱 / 水冷 / 熱管理',
                            'parent': 'AI 伺服器與資料中心',
                            'primary_valuation': 'forward_pe',
                            'secondary_valuation': ['eps_revision', 'revenue_growth', 'gross_margin', 'liquid_cooling_penetration'],
                            'valuation_focus': ['Forward P/E', 'EPS 上修', '月營收', '毛利率', '液冷滲透率'],
                            'base_pe': 34,
                            'pe_range': (24, 60),
                            'base_pb': None,
                            'pb_range': None,
                            'cyclical': False,
                            'pe_applicable': True,
                            'pe_trap_warning': False,
                            'theme_premium_allowed': True,
                            'liquidity_sensitive': True,
                            'operable_discount_factor': 0.86,
                            'risk_flags': ['估值過熱', '月營收轉弱', '競爭者擴產', '法人下修', '題材鈍化'],
                            'note': 'AI 水冷題材可給較高 Cap，但可操作估值需折價。',
                            'floor_pe': 18,
                            'soft_ceiling_pe': 48,
                            'hard_ceiling_pe': 60,
                            'max_growth_factor': 1.18,
                            'max_quality_factor': 1.16,
                            'max_theme_factor': 1.1,
                            'max_scale_factor': 1.06,
                            'gross_margin_baseline': 0.26,
                            'gross_margin_good': 0.32,
                            'gross_margin_excellent': 0.4,
                            'baked_in_themes': ['水冷', '液冷', '散熱'],
                            'calibration_source': '17-B-2 全產業校準表'},
 'OPTICAL_COMM_SILICON_PHOTONICS': {'display_name': '光通訊 / 矽光子 / CPO',
                                    'parent': '光通訊與網通',
                                    'primary_valuation': 'forward_pe',
                                    'secondary_valuation': ['revenue_growth', 'gross_margin', 'customer_validation', 'spec_upgrade'],
                                    'valuation_focus': ['Forward P/E', '800G/1.6T/CPO', '營收動能', '毛利率', '客戶認證'],
                                    'base_pe': 36,
                                    'pe_range': (24, 68),
                                    'base_pb': None,
                                    'pb_range': None,
                                    'cyclical': False,
                                    'pe_applicable': True,
                                    'pe_trap_warning': False,
                                    'theme_premium_allowed': True,
                                    'liquidity_sensitive': True,
                                    'operable_discount_factor': 0.84,
                                    'risk_flags': ['客戶認證失敗', '規格轉換', '題材波動', '法人樣本不足', '單月營收大幅波動'],
                                    'note': '矽光子/CPO 題材強，但需降低未落地營收的估值可信度。',
                                    'floor_pe': 20,
                                    'soft_ceiling_pe': 54,
                                    'hard_ceiling_pe': 68,
                                    'max_growth_factor': 1.2,
                                    'max_quality_factor': 1.16,
                                    'max_theme_factor': 1.1,
                                    'max_scale_factor': 1.06,
                                    'gross_margin_baseline': 0.32,
                                    'gross_margin_good': 0.4,
                                    'gross_margin_excellent': 0.48,
                                    'baked_in_themes': ['矽光子', 'CPO', '800G', '1.6T'],
                                    'calibration_source': '17-B-2 全產業校準表'},
 'NETWORK_SWITCH': {'display_name': '網通 / 交換器 / 資料中心網路',
                    'parent': '光通訊與網通',
                    'primary_valuation': 'forward_pe',
                    'secondary_valuation': ['revenue_growth', 'gross_margin', 'switch_upgrade'],
                    'valuation_focus': ['Forward P/E', '交換器規格升級', '營收成長', '毛利率'],
                    'base_pe': 26,
                    'pe_range': (16, 45),
                    'base_pb': None,
                    'pb_range': None,
                    'cyclical': False,
                    'pe_applicable': True,
                    'pe_trap_warning': False,
                    'theme_premium_allowed': True,
                    'liquidity_sensitive': True,
                    'operable_discount_factor': 0.9,
                    'risk_flags': ['客戶換代時程', '庫存調整', '產品組合', '毛利率下滑'],
                    'note': 'AI switch 受惠股可高於傳統網通，但需看規格與訂單落地。',
                    'floor_pe': 14,
                    'soft_ceiling_pe': 36,
                    'hard_ceiling_pe': 45,
                    'max_growth_factor': 1.14,
                    'max_quality_factor': 1.12,
                    'max_theme_factor': 1.06,
                    'max_scale_factor': 1.04,
                    'gross_margin_baseline': 0.24,
                    'gross_margin_good': 0.32,
                    'gross_margin_excellent': 0.4,
                    'baked_in_themes': ['交換器', '網通'],
                    'calibration_source': '17-B-2 全產業校準表'},
 'OPTICS_LENS_MODULE': {'display_name': '光學 / 鏡頭 / 光學模組',
                        'parent': '光學與感測',
                        'primary_valuation': 'forward_pe',
                        'secondary_valuation': ['gross_margin', 'roe', 'product_cycle', 'customer_validation'],
                        'valuation_focus': ['Forward P/E', '毛利率', 'ROE', '產品週期', '車載/AI 光學導入'],
                        'base_pe': 28,
                        'pe_range': (18, 50),
                        'base_pb': None,
                        'pb_range': None,
                        'cyclical': False,
                        'pe_applicable': True,
                        'pe_trap_warning': False,
                        'theme_premium_allowed': True,
                        'liquidity_sensitive': True,
                        'operable_discount_factor': 0.9,
                        'risk_flags': ['手機產品週期', '客戶集中', '規格升級不如預期', '毛利率下滑'],
                        'note': '光學鏡頭不同於面板光電循環，需獨立估值。',
                        'floor_pe': 16,
                        'soft_ceiling_pe': 40,
                        'hard_ceiling_pe': 50,
                        'max_growth_factor': 1.16,
                        'max_quality_factor': 1.18,
                        'max_theme_factor': 1.06,
                        'max_scale_factor': 1.04,
                        'gross_margin_baseline': 0.38,
                        'gross_margin_good': 0.48,
                        'gross_margin_excellent': 0.58,
                        'baked_in_themes': ['光學', '鏡頭'],
                        'calibration_source': '17-B-2 全產業校準表'},
 'ROBOTICS_AUTOMATION': {'display_name': '機器人 / 智慧自動化',
                         'parent': '自動化與機器人',
                         'primary_valuation': 'forward_pe',
                         'secondary_valuation': ['orders', 'gross_margin', 'cycle_position', 'customer_validation'],
                         'valuation_focus': ['Forward P/E', '訂單', '毛利率', '景氣循環', '機器視覺/傳動/控制'],
                         'base_pe': 24,
                         'pe_range': (16, 45),
                         'base_pb': None,
                         'pb_range': None,
                         'cyclical': True,
                         'pe_applicable': 'conditional',
                         'pe_trap_warning': False,
                         'theme_premium_allowed': True,
                         'liquidity_sensitive': True,
                         'operable_discount_factor': 0.9,
                         'risk_flags': ['工具機循環', '題材未落地', '訂單遞延', '中國景氣', 'EPS/訂單未落地時切換事件模型'],
                         'note': '自動化設備有穩定 EPS 可用 P/E；純機器人題材或 EPS 未落地時改用事件模型',
                         'floor_pe': 14,
                         'soft_ceiling_pe': 36,
                         'hard_ceiling_pe': 45,
                         'max_growth_factor': 1.14,
                         'max_quality_factor': 1.12,
                         'max_theme_factor': 1.06,
                         'max_scale_factor': 1.04,
                         'gross_margin_baseline': 0.28,
                         'gross_margin_good': 0.36,
                         'gross_margin_excellent': 0.45,
                         'baked_in_themes': ['機器人', '自動化'],
                         'event_model_if_eps_unstable': True,
                         'event_switch_note': '自動化設備有穩定 EPS 可用 P/E；純機器人題材或 EPS 未落地時改用事件模型',
                         'calibration_source': '17-B-2 全產業校準表'},
 'SPACE_LEO_SATELLITE': {'display_name': '太空科技 / 低軌衛星 / 無人載具',
                         'parent': '太空科技與航太',
                         'primary_valuation': 'forward_pe_or_event',
                         'secondary_valuation': ['orders', 'customer_validation', 'gross_margin', 'event_milestone'],
                         'valuation_focus': ['Forward P/E', '訂單', '客戶認證', '地面終端', 'RF/毫米波', '事件里程碑'],
                         'base_pe': 28,
                         'pe_range': (18, 45),
                         'base_pb': None,
                         'pb_range': None,
                         'cyclical': False,
                         'pe_applicable': 'conditional',
                         'pe_trap_warning': True,
                         'theme_premium_allowed': True,
                         'liquidity_sensitive': True,
                         'operable_discount_factor': 0.82,
                         'risk_flags': ['題材先漲', '訂單未確認', '政策事件', '籌碼急轉', 'EPS 未落地', 'EPS/訂單未落地時切換事件模型'],
                         'note': '低軌衛星若訂單與 EPS 尚未落地，改用事件 / 訂單驗證模型；有穩定 EPS 才採 P/E',
                         'floor_pe': 14,
                         'soft_ceiling_pe': 34,
                         'hard_ceiling_pe': 45,
                         'max_growth_factor': 1.12,
                         'max_quality_factor': 1.1,
                         'max_theme_factor': 1.05,
                         'max_scale_factor': 1.04,
                         'gross_margin_baseline': 0.25,
                         'gross_margin_good': 0.33,
                         'gross_margin_excellent': 0.42,
                         'baked_in_themes': ['低軌', '衛星', '太空'],
                         'event_model_if_eps_unstable': True,
                         'event_switch_note': '低軌衛星若訂單與 EPS 尚未落地，改用事件 / 訂單驗證模型；有穩定 EPS 才採 P/E',
                         'calibration_source': '17-B-2 全產業校準表'},
 'EV_AUTO_ELECTRONICS': {'display_name': '車用電子 / 電動車零組件',
                         'parent': '車用電子與電動車',
                         'primary_valuation': 'forward_pe',
                         'secondary_valuation': ['certification_cycle', 'orders', 'gross_margin', 'revenue_growth'],
                         'valuation_focus': ['Forward P/E', '認證週期', '訂單穩定度', '毛利率', '車用占比'],
                         'base_pe': 26,
                         'pe_range': (16, 45),
                         'base_pb': None,
                         'pb_range': None,
                         'cyclical': False,
                         'pe_applicable': True,
                         'pe_trap_warning': False,
                         'theme_premium_allowed': True,
                         'liquidity_sensitive': True,
                         'operable_discount_factor': 0.92,
                         'risk_flags': ['車廠庫存', '認證延遲', '價格競爭', 'EV 需求波動'],
                         'note': '車用電子認證期長、訂單黏著度高，估值邏輯不同於消費電子。',
                         'floor_pe': 14,
                         'soft_ceiling_pe': 36,
                         'hard_ceiling_pe': 45,
                         'max_growth_factor': 1.14,
                         'max_quality_factor': 1.12,
                         'max_theme_factor': 1.06,
                         'max_scale_factor': 1.04,
                         'gross_margin_baseline': 0.22,
                         'gross_margin_good': 0.3,
                         'gross_margin_excellent': 0.38,
                         'baked_in_themes': ['車用', '電動車'],
                         'calibration_source': '17-B-2 全產業校準表'},
 'GRID_POWER_STORAGE': {'display_name': '重電 / 電網 / 儲能',
                        'parent': '電力基建與能源',
                        'primary_valuation': 'forward_pe_orders',
                        'secondary_valuation': ['order_backlog', 'policy_spending', 'gross_margin', 'cash_flow'],
                        'valuation_focus': ['Forward P/E', '訂單能見度', '台電/海外標案', '毛利率', '現金流'],
                        'base_pe': 28,
                        'pe_range': (16, 42),
                        'base_pb': None,
                        'pb_range': None,
                        'cyclical': False,
                        'pe_applicable': True,
                        'pe_trap_warning': False,
                        'theme_premium_allowed': True,
                        'liquidity_sensitive': True,
                        'operable_discount_factor': 0.9,
                        'risk_flags': ['政策標案時程', '交貨認列', '原物料成本', '漲多估值修正'],
                        'note': '重電與工具機不可混用；重電可享長單與基建溢價。',
                        'floor_pe': 14,
                        'soft_ceiling_pe': 36,
                        'hard_ceiling_pe': 42,
                        'max_growth_factor': 1.14,
                        'max_quality_factor': 1.12,
                        'max_theme_factor': 1.06,
                        'max_scale_factor': 1.04,
                        'gross_margin_baseline': 0.18,
                        'gross_margin_good': 0.24,
                        'gross_margin_excellent': 0.3,
                        'baked_in_themes': ['重電', '電網', '儲能'],
                        'calibration_source': '17-B-2 全產業校準表'},
 'SOFTWARE_SECURITY_CLOUD': {'display_name': '軟體 / 資安 / 雲端 / 系統整合',
                             'parent': '軟體與資訊服務',
                             'primary_valuation': 'pe_fcf_growth',
                             'secondary_valuation': ['revenue_growth', 'gross_margin', 'fcf', 'recurring_revenue'],
                             'valuation_focus': ['P/E', '營收成長', '毛利率', 'FCF', '經常性收入'],
                             'base_pe': 30,
                             'pe_range': (18, 50),
                             'base_pb': None,
                             'pb_range': None,
                             'cyclical': False,
                             'pe_applicable': True,
                             'pe_trap_warning': False,
                             'theme_premium_allowed': False,
                             'liquidity_sensitive': True,
                             'operable_discount_factor': 0.92,
                             'risk_flags': ['專案認列遞延', '人力成本', '政府標案時程', 'AI 題材未落地'],
                             'note': '有穩定獲利者可用 P/E；純 AI 軟體題材不給獨立高倍率。',
                             'floor_pe': 16,
                             'soft_ceiling_pe': 42,
                             'hard_ceiling_pe': 50,
                             'max_growth_factor': 1.18,
                             'max_quality_factor': 1.18,
                             'max_theme_factor': 1.06,
                             'max_scale_factor': 1.04,
                             'gross_margin_baseline': 0.45,
                             'gross_margin_good': 0.55,
                             'gross_margin_excellent': 0.65,
                             'baked_in_themes': ['資安', '雲端', '軟體'],
                             'calibration_source': '17-B-2 全產業校準表'},
 'MEMORY_CYCLE': {'display_name': '記憶體 / DRAM / NAND / 模組',
                  'parent': '循環電子',
                  'primary_valuation': 'pb_cycle',
                  'secondary_valuation': ['spot_price', 'inventory_cycle', 'revenue_growth', 'gross_margin'],
                  'valuation_focus': ['P/B', '報價循環', '庫存週期', '月營收', '毛利率'],
                  'base_pe': None,
                  'pe_range': None,
                  'base_pb': 1.2,
                  'pb_range': (0.8, 2.2),
                  'cyclical': True,
                  'pe_applicable': 'secondary_only',
                  'pe_trap_warning': True,
                  'theme_premium_allowed': False,
                  'liquidity_sensitive': True,
                  'operable_discount_factor': 0.86,
                  'risk_flags': ['景氣高峰低 P/E 陷阱', '庫存修正', '報價下跌', 'P/E 失真'],
                  'note': '記憶體需優先用 P/B 與報價循環，低 P/E 不一定代表低估。',
                  'calibration_source': '17-B-2 全產業校準表'},
 'DISPLAY_LED_CYCLE': {'display_name': '面板 / LED / 光電循環',
                       'parent': '循環電子',
                       'primary_valuation': 'pb_cycle',
                       'secondary_valuation': ['panel_price', 'utilization', 'revenue_growth'],
                       'valuation_focus': ['P/B', '報價循環', '產能利用率', '月營收'],
                       'base_pe': None,
                       'pe_range': None,
                       'base_pb': 0.9,
                       'pb_range': (0.5, 1.5),
                       'cyclical': True,
                       'pe_applicable': 'secondary_only',
                       'pe_trap_warning': True,
                       'theme_premium_allowed': False,
                       'liquidity_sensitive': True,
                       'operable_discount_factor': 0.84,
                       'risk_flags': ['面板報價反轉', '產能過剩', 'P/E 失真', '景氣高峰低 P/E 陷阱'],
                       'note': '面板/LED 與高階光學鏡頭必須分開估值。',
                       'calibration_source': '17-B-2 全產業校準表'},
 'PASSIVE_COMPONENT_CYCLE': {'display_name': '被動元件 / 電容電阻電感',
                             'parent': '循環電子',
                             'primary_valuation': 'pb_cycle',
                             'secondary_valuation': ['pricing_cycle', 'inventory', 'revenue_growth', 'gross_margin'],
                             'valuation_focus': ['P/B', '報價循環', '庫存', '毛利率', '月營收'],
                             'base_pe': None,
                             'pe_range': None,
                             'base_pb': 1.4,
                             'pb_range': (0.8, 2.5),
                             'cyclical': True,
                             'pe_applicable': 'secondary_only',
                             'pe_trap_warning': True,
                             'theme_premium_allowed': False,
                             'liquidity_sensitive': True,
                             'operable_discount_factor': 0.86,
                             'risk_flags': ['庫存修正', '報價下跌', '景氣高峰低 P/E 陷阱', '需求轉弱'],
                             'note': '被動元件需看庫存與報價，P/E 只能輔助。',
                             'calibration_source': '17-B-2 全產業校準表'},
 'FINANCIAL': {'display_name': '金融 / 金控 / 銀行 / 保險',
               'parent': '金融',
               'primary_valuation': 'pb_roe_dividend',
               'secondary_valuation': ['roe', 'dividend_yield', 'capital_adequacy'],
               'valuation_focus': ['P/B', 'ROE', '殖利率', '資本適足率', '利率循環'],
               'base_pe': None,
               'pe_range': None,
               'base_pb': 1.1,
               'pb_range': (0.8, 1.8),
               'cyclical': True,
               'pe_applicable': 'secondary_only',
               'pe_trap_warning': True,
               'theme_premium_allowed': False,
               'liquidity_sensitive': False,
               'operable_discount_factor': 0.95,
               'risk_flags': ['利率循環', '保險匯損', '資產品質', 'P/E 不適合作為主估值'],
               'note': '金融以 P/B 與 ROE 為主，不應使用科技股 P/E Cap。',
               'calibration_source': '17-B-2 全產業校準表'},
 'TRADITIONAL_CYCLE': {'display_name': '傳產循環 / 原物料 / 化工 / 鋼鐵',
                       'parent': '非電子循環',
                       'primary_valuation': 'pb_cycle',
                       'secondary_valuation': ['spread_cycle', 'cash_flow', 'dividend_yield'],
                       'valuation_focus': ['P/B', '產品利差', '景氣循環', '現金流', '殖利率'],
                       'base_pe': None,
                       'pe_range': None,
                       'base_pb': 1.0,
                       'pb_range': (0.6, 1.8),
                       'cyclical': True,
                       'pe_applicable': 'secondary_only',
                       'pe_trap_warning': True,
                       'theme_premium_allowed': False,
                       'liquidity_sensitive': True,
                       'operable_discount_factor': 0.88,
                       'risk_flags': ['景氣高峰低 P/E 陷阱', '原物料利差反轉', '需求循環', '現金流波動'],
                       'note': '傳產循環優先看 P/B、利差與景氣位置。',
                       'calibration_source': '17-B-2 全產業校準表'},
 'SHIPPING_CYCLE': {'display_name': '航運 / 空運 / 物流循環',
                    'parent': '非電子循環',
                    'primary_valuation': 'pb_cycle_freight',
                    'secondary_valuation': ['freight_rate', 'dividend_yield', 'cash_flow'],
                    'valuation_focus': ['P/B', '運價', '景氣循環', '殖利率', '現金流'],
                    'base_pe': None,
                    'pe_range': None,
                    'base_pb': 0.9,
                    'pb_range': (0.5, 1.8),
                    'cyclical': True,
                    'pe_applicable': 'secondary_only',
                    'pe_trap_warning': True,
                    'theme_premium_allowed': False,
                    'liquidity_sensitive': True,
                    'operable_discount_factor': 0.82,
                    'risk_flags': ['景氣高峰低 P/E 陷阱', '運價反轉', '高殖利率不可持續', '景氣急轉'],
                    'note': '航運不應硬套 P/E；需以 P/B 與運價週期為主。',
                    'calibration_source': '17-B-2 全產業校準表'},
 'BIOTECH_MEDICAL': {'display_name': '生技醫療 / 藥廠 / 醫材',
                     'parent': '生技醫療',
                     'primary_valuation': 'pe_or_milestone',
                     'secondary_valuation': ['gross_margin', 'pipeline', 'cash_flow', 'regulatory_milestones'],
                     'valuation_focus': ['P/E', '毛利率', '研發里程碑', '現金流', '法規進度'],
                     'base_pe': 28,
                     'pe_range': (18, 45),
                     'base_pb': None,
                     'pb_range': None,
                     'cyclical': False,
                     'pe_applicable': 'conditional',
                     'pe_trap_warning': True,
                     'theme_premium_allowed': True,
                     'liquidity_sensitive': True,
                     'operable_discount_factor': 0.82,
                     'risk_flags': ['新藥里程碑失敗', '法規風險', '現金流不足', 'EPS 不穩', 'EPS/訂單未落地時切換事件模型'],
                     'note': '成熟藥廠 / 醫材有 EPS 可用 P/E；新藥題材或 EPS 未落地改用里程碑事件模型',
                     'floor_pe': 12,
                     'soft_ceiling_pe': 35,
                     'hard_ceiling_pe': 45,
                     'max_growth_factor': 1.16,
                     'max_quality_factor': 1.14,
                     'max_theme_factor': 1.04,
                     'max_scale_factor': 1.04,
                     'gross_margin_baseline': 0.45,
                     'gross_margin_good': 0.55,
                     'gross_margin_excellent': 0.65,
                     'event_model_if_eps_unstable': True,
                     'event_switch_note': '成熟藥廠 / 醫材有 EPS 可用 P/E；新藥題材或 EPS 未落地改用里程碑事件模型',
                     'calibration_source': '17-B-2 全產業校準表'},
 'CONSUMER_TOURISM': {'display_name': '消費 / 觀光 / 生活產業',
                      'parent': '消費服務',
                      'primary_valuation': 'pe_cashflow',
                      'secondary_valuation': ['same_store_sales', 'expansion', 'dividend_yield', 'cash_flow'],
                      'valuation_focus': ['P/E', '現金流', '展店', '同店成長', '殖利率'],
                      'base_pe': 22,
                      'pe_range': (12, 38),
                      'base_pb': None,
                      'pb_range': None,
                      'cyclical': False,
                      'pe_applicable': True,
                      'pe_trap_warning': False,
                      'theme_premium_allowed': False,
                      'liquidity_sensitive': True,
                      'operable_discount_factor': 0.92,
                      'risk_flags': ['消費景氣', '展店不如預期', '成本上升', '人力成本'],
                      'note': '消費與觀光以現金流、展店與同店成長為主。',
                      'floor_pe': 10,
                      'soft_ceiling_pe': 32,
                      'hard_ceiling_pe': 38,
                      'max_growth_factor': 1.12,
                      'max_quality_factor': 1.1,
                      'max_theme_factor': 1.02,
                      'max_scale_factor': 1.03,
                      'gross_margin_baseline': 0.3,
                      'gross_margin_good': 0.38,
                      'gross_margin_excellent': 0.45,
                      'calibration_source': '17-B-2 全產業校準表'},
 'THEME_EVENT': {'display_name': '題材 / 事件驅動股',
                 'parent': '特殊題材',
                 'primary_valuation': 'event_chip',
                 'secondary_valuation': ['orders', 'catalysts', 'volume', 'financial_delivery'],
                 'valuation_focus': ['事件催化', '訂單真實性', '籌碼', '成交量', '財報落地程度'],
                 'base_pe': None,
                 'pe_range': None,
                 'base_pb': None,
                 'pb_range': None,
                 'cyclical': False,
                 'pe_applicable': False,
                 'pe_trap_warning': True,
                 'theme_premium_allowed': False,
                 'liquidity_sensitive': True,
                 'operable_discount_factor': 0.6,
                 'risk_flags': ['EPS 未支撐', '法人目標不足', '籌碼急轉', '消息鈍化', '不適合一般 P/E 買進模型'],
                 'note': '題材股不輸出 P/E 買進倍率；只可作事件與籌碼風險提示。'},
 'GENERAL': {'display_name': '一般產業 / 尚未分類',
             'parent': '未分類',
             'primary_valuation': 'pe_pb_crosscheck',
             'secondary_valuation': ['roe', 'revenue_growth', 'fcf'],
             'valuation_focus': ['P/E', 'P/B', 'ROE', '月營收', 'FCF'],
             'base_pe': 18,
             'pe_range': (10, 35),
             'base_pb': None,
             'pb_range': None,
             'cyclical': False,
             'pe_applicable': True,
             'pe_trap_warning': False,
             'theme_premium_allowed': False,
             'liquidity_sensitive': True,
             'operable_discount_factor': 0.95,
             'risk_flags': ['分類不足', '資料不足', 'AI/系統分歧'],
             'note': '通用模型；建議人工確認產業後再提高可信度。',
             'floor_pe': 8,
             'soft_ceiling_pe': 28,
             'hard_ceiling_pe': 35,
             'max_growth_factor': 1.1,
             'max_quality_factor': 1.08,
             'max_theme_factor': 1.03,
             'max_scale_factor': 1.02,
             'calibration_source': '17-B-2 全產業校準表'}}


def get_taxonomy(taxon_key: str):
    """安全取得產業分類設定。"""
    if not taxon_key:
        return INDUSTRY_TAXONOMY["GENERAL"]
    return INDUSTRY_TAXONOMY.get(str(taxon_key).strip().upper(), INDUSTRY_TAXONOMY["GENERAL"])
