"""
台股 2.0 產業估值分類表（第 17-A 階段）。

用途：
- 定義各產業的主要估值模型、P/E 或 P/B 適用性、循環股警示與風險旗標。
- 不直接計算動態 Cap 2.0；第 17-B 才會將本表接入倍率加總與折扣模型。
"""

INDUSTRY_TAXONOMY = {
    "FOUNDRY": {
        "display_name": "晶圓代工 / HPC / 先進製程",
        "parent": "半導體核心",
        "primary_valuation": "forward_pe",
        "secondary_valuation": ["pb", "roe", "gross_margin", "capex_cycle"],
        "valuation_focus": ["Forward P/E", "P/B", "ROE", "毛利率", "產能利用率", "資本支出"],
        "base_pe": 32, "pe_range": (25, 42), "base_pb": None, "pb_range": None,
        "cyclical": True, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": True, "liquidity_sensitive": False,
        "operable_discount_factor": 0.96,
        "risk_flags": ["景氣循環", "資本支出高峰", "毛利率下滑", "先進製程競爭", "匯率"],
        "note": "可使用 P/E/Forward P/E，但需搭配 P/B、ROE 與毛利率交叉驗證。",
    },
    "IC_DESIGN_ASIC": {
        "display_name": "IC 設計 / ASIC / AI 晶片",
        "parent": "半導體核心",
        "primary_valuation": "forward_pe",
        "secondary_valuation": ["eps_cagr", "gross_margin", "roe", "revenue_growth"],
        "valuation_focus": ["Forward P/E", "EPS CAGR", "毛利率", "ROE", "AI ASIC 訂單"],
        "base_pe": 45, "pe_range": (35, 78), "base_pb": None, "pb_range": None,
        "cyclical": False, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": True, "liquidity_sensitive": True,
        "operable_discount_factor": 0.90,
        "risk_flags": ["客戶集中", "AI 訂單未確認", "高基期", "毛利率下滑", "庫存修正"],
        "note": "高毛利與 ASIC 題材可給較高倍率，但需確認 EPS 是否真的上修。",
    },
    "IP_EDA_DESIGN_SERVICE": {
        "display_name": "IP / EDA / 設計服務 / 矽智財",
        "parent": "半導體核心",
        "primary_valuation": "forward_pe",
        "secondary_valuation": ["gross_margin", "recurring_revenue", "roe"],
        "valuation_focus": ["Forward P/E", "毛利率", "授權收入", "ROE", "設計案能見度"],
        "base_pe": 48, "pe_range": (38, 85), "base_pb": None, "pb_range": None,
        "cyclical": False, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": True, "liquidity_sensitive": True,
        "operable_discount_factor": 0.88,
        "risk_flags": ["授權收入波動", "設計案延後", "客戶集中", "估值過高"],
        "note": "高毛利 IP/EDA 類可給高估值，但需以營收落地與現金流驗證。",
    },
    "OSAT_TESTING": {
        "display_name": "封測 / 測試 / 先進封裝服務",
        "parent": "半導體核心",
        "primary_valuation": "forward_pe",
        "secondary_valuation": ["utilization", "capex_cycle", "gross_margin", "pb"],
        "valuation_focus": ["Forward P/E", "稼動率", "先進封裝占比", "毛利率", "資本支出"],
        "base_pe": 28, "pe_range": (20, 42), "base_pb": None, "pb_range": None,
        "cyclical": True, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": True, "liquidity_sensitive": False,
        "operable_discount_factor": 0.94,
        "risk_flags": ["稼動率下降", "資本支出高峰", "庫存修正", "價格競爭"],
        "note": "封測有循環性，先進封裝比重提高時可提升估值。",
    },
    "PROBE_TEST_INTERFACE": {
        "display_name": "探針卡 / 測試介面 / 半導體檢測",
        "parent": "半導體設備與耗材",
        "primary_valuation": "forward_pe",
        "secondary_valuation": ["gross_margin", "orders", "revenue_growth", "fcf"],
        "valuation_focus": ["Forward P/E", "毛利率", "訂單能見度", "客戶導入", "FCF"],
        "base_pe": 40, "pe_range": (30, 65), "base_pb": None, "pb_range": None,
        "cyclical": False, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": True, "liquidity_sensitive": True,
        "operable_discount_factor": 0.90,
        "risk_flags": ["訂單遞延", "客戶驗證不確定", "EPS 預估分歧", "高估值修正"],
        "note": "高毛利檢測介面可給成長溢價，但需看導入時程。",
    },
    "SEMICAP_COWOS_EQUIPMENT": {
        "display_name": "CoWoS / 先進封裝 / 半導體設備",
        "parent": "半導體設備與耗材",
        "primary_valuation": "forward_pe",
        "secondary_valuation": ["orders", "gross_margin", "fcf", "revenue_growth"],
        "valuation_focus": ["Forward P/E", "訂單能見度", "毛利率", "FCF", "交期"],
        "base_pe": 40, "pe_range": (32, 65), "base_pb": None, "pb_range": None,
        "cyclical": False, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": True, "liquidity_sensitive": True,
        "operable_discount_factor": 0.88,
        "risk_flags": ["認列時程", "客戶驗證", "單月營收轉弱", "法人下修", "高估值"],
        "note": "CoWoS 設備可享 AI 題材溢價，但需要訂單與 EPS 同步驗證。",
    },
    "FAB_FACILITY_MATERIALS": {
        "display_name": "半導體廠務 / 材料 / 製程耗材",
        "parent": "半導體設備與耗材",
        "primary_valuation": "pe_fcf",
        "secondary_valuation": ["orders", "gross_margin", "pb", "capex_cycle"],
        "valuation_focus": ["P/E", "訂單", "FCF", "毛利率", "晶圓廠資本支出"],
        "base_pe": 30, "pe_range": (22, 48), "base_pb": None, "pb_range": None,
        "cyclical": True, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": True, "liquidity_sensitive": True,
        "operable_discount_factor": 0.92,
        "risk_flags": ["資本支出循環", "專案認列", "毛利率波動", "現金流遞延"],
        "note": "廠務與耗材需看訂單、現金流與台積電/美國建廠週期。",
    },
    "ABF_SUBSTRATE": {
        "display_name": "PCB / ABF / 高階載板",
        "parent": "PCB / 載板",
        "primary_valuation": "forward_pe",
        "secondary_valuation": ["pb", "revenue_growth", "gross_margin", "pricing_cycle"],
        "valuation_focus": ["Forward P/E", "P/B", "月營收", "毛利率", "ABF 報價循環"],
        "base_pe": 38, "pe_range": (30, 60), "base_pb": None, "pb_range": None,
        "cyclical": True, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": True, "liquidity_sensitive": True,
        "operable_discount_factor": 0.90,
        "risk_flags": ["ABF 報價轉弱", "單月營收衰退", "EPS 預估分歧", "庫存調整"],
        "note": "載板不宜只看 TTM P/E；需看 Forward EPS 與報價循環。",
    },
    "SERVER_PCB_BOARD": {
        "display_name": "AI 伺服器主板 / 高階 PCB",
        "parent": "PCB / 載板",
        "primary_valuation": "forward_pe",
        "secondary_valuation": ["revenue_growth", "gross_margin", "server_mix"],
        "valuation_focus": ["Forward P/E", "營收 YoY", "毛利率", "伺服器占比", "客戶訂單"],
        "base_pe": 35, "pe_range": (26, 55), "base_pb": None, "pb_range": None,
        "cyclical": True, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": True, "liquidity_sensitive": True,
        "operable_discount_factor": 0.90,
        "risk_flags": ["AI 出貨高峰", "客戶集中", "單月營收轉弱", "毛利率下滑"],
        "note": "高階 PCB 需分清一般板與 AI 伺服器高階板。",
    },
    "AI_SERVER_ODM": {
        "display_name": "AI 伺服器 ODM / 組裝",
        "parent": "AI 伺服器與資料中心",
        "primary_valuation": "forward_pe",
        "secondary_valuation": ["revenue_growth", "gross_margin", "inventory", "customer_orders"],
        "valuation_focus": ["Forward P/E", "營收動能", "毛利率", "AI 伺服器占比", "客戶訂單"],
        "base_pe": 28, "pe_range": (20, 45), "base_pb": None, "pb_range": None,
        "cyclical": False, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": True, "liquidity_sensitive": False,
        "operable_discount_factor": 0.92,
        "risk_flags": ["低毛利", "客戶砍單", "高基期", "匯率", "出貨高峰後衰退"],
        "note": "ODM 出貨量大但毛利低，題材溢價需受毛利率約束。",
    },
    "CONNECTOR_CABLE": {
        "display_name": "高速連接器 / 線材 / 高速傳輸",
        "parent": "AI 伺服器與資料中心",
        "primary_valuation": "forward_pe",
        "secondary_valuation": ["gross_margin", "spec_upgrade", "customer_validation"],
        "valuation_focus": ["Forward P/E", "毛利率", "規格升級", "高速傳輸", "客戶認證"],
        "base_pe": 36, "pe_range": (28, 58), "base_pb": None, "pb_range": None,
        "cyclical": False, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": True, "liquidity_sensitive": True,
        "operable_discount_factor": 0.90,
        "risk_flags": ["規格轉換", "客戶認證延遲", "產品組合變化", "毛利率下滑"],
        "note": "高速傳輸與車用認證可提高估值穩定度。",
    },
    "SERVER_CHASSIS_RAIL": {
        "display_name": "機殼 / 滑軌 / 機構件",
        "parent": "AI 伺服器與資料中心",
        "primary_valuation": "forward_pe",
        "secondary_valuation": ["orders", "gross_margin", "revenue_growth"],
        "valuation_focus": ["Forward P/E", "訂單", "毛利率", "伺服器機構件占比"],
        "base_pe": 30, "pe_range": (22, 48), "base_pb": None, "pb_range": None,
        "cyclical": False, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": True, "liquidity_sensitive": True,
        "operable_discount_factor": 0.91,
        "risk_flags": ["訂單遞延", "價格競爭", "毛利率下滑", "客戶集中"],
        "note": "機構件需看 AI 機櫃占比與出貨能見度。",
    },
    "POWER_BBU": {
        "display_name": "電源供應 / BBU / 電源模組",
        "parent": "AI 伺服器與資料中心",
        "primary_valuation": "forward_pe",
        "secondary_valuation": ["gross_margin", "server_mix", "revenue_growth"],
        "valuation_focus": ["Forward P/E", "毛利率", "BBU/高瓦數 PSU", "AI 伺服器占比"],
        "base_pe": 30, "pe_range": (22, 48), "base_pb": None, "pb_range": None,
        "cyclical": False, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": True, "liquidity_sensitive": True,
        "operable_discount_factor": 0.92,
        "risk_flags": ["出貨時程", "毛利率變化", "客戶集中", "價格競爭"],
        "note": "高瓦數 PSU/BBU 可享 AI 溢價，但不能與低毛利產品混算。",
    },
    "THERMAL_LIQUID_COOLING": {
        "display_name": "散熱 / 水冷 / 熱管理",
        "parent": "AI 伺服器與資料中心",
        "primary_valuation": "forward_pe",
        "secondary_valuation": ["eps_revision", "revenue_growth", "gross_margin", "liquid_cooling_penetration"],
        "valuation_focus": ["Forward P/E", "EPS 上修", "月營收", "毛利率", "液冷滲透率"],
        "base_pe": 42, "pe_range": (32, 68), "base_pb": None, "pb_range": None,
        "cyclical": False, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": True, "liquidity_sensitive": True,
        "operable_discount_factor": 0.86,
        "risk_flags": ["估值過熱", "月營收轉弱", "競爭者擴產", "法人下修", "題材鈍化"],
        "note": "AI 水冷題材可給較高 Cap，但可操作估值需折價。",
    },
    "OPTICAL_COMM_SILICON_PHOTONICS": {
        "display_name": "光通訊 / 矽光子 / CPO",
        "parent": "光通訊與網通",
        "primary_valuation": "forward_pe",
        "secondary_valuation": ["revenue_growth", "gross_margin", "customer_validation", "spec_upgrade"],
        "valuation_focus": ["Forward P/E", "800G/1.6T/CPO", "營收動能", "毛利率", "客戶認證"],
        "base_pe": 45, "pe_range": (35, 78), "base_pb": None, "pb_range": None,
        "cyclical": False, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": True, "liquidity_sensitive": True,
        "operable_discount_factor": 0.84,
        "risk_flags": ["客戶認證失敗", "規格轉換", "題材波動", "法人樣本不足", "單月營收大幅波動"],
        "note": "矽光子/CPO 題材強，但需降低未落地營收的估值可信度。",
    },
    "NETWORK_SWITCH": {
        "display_name": "網通 / 交換器 / 資料中心網路",
        "parent": "光通訊與網通",
        "primary_valuation": "forward_pe",
        "secondary_valuation": ["revenue_growth", "gross_margin", "switch_upgrade"],
        "valuation_focus": ["Forward P/E", "交換器規格升級", "營收成長", "毛利率"],
        "base_pe": 34, "pe_range": (25, 55), "base_pb": None, "pb_range": None,
        "cyclical": False, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": True, "liquidity_sensitive": True,
        "operable_discount_factor": 0.90,
        "risk_flags": ["客戶換代時程", "庫存調整", "產品組合", "毛利率下滑"],
        "note": "AI switch 受惠股可高於傳統網通，但需看規格與訂單落地。",
    },
    "OPTICS_LENS_MODULE": {
        "display_name": "光學 / 鏡頭 / 光學模組",
        "parent": "光學與感測",
        "primary_valuation": "forward_pe",
        "secondary_valuation": ["gross_margin", "roe", "product_cycle", "customer_validation"],
        "valuation_focus": ["Forward P/E", "毛利率", "ROE", "產品週期", "車載/AI 光學導入"],
        "base_pe": 35, "pe_range": (25, 60), "base_pb": None, "pb_range": None,
        "cyclical": False, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": True, "liquidity_sensitive": True,
        "operable_discount_factor": 0.90,
        "risk_flags": ["手機產品週期", "客戶集中", "規格升級不如預期", "毛利率下滑"],
        "note": "光學鏡頭不同於面板光電循環，需獨立估值。",
    },
    "ROBOTICS_AUTOMATION": {
        "display_name": "機器人 / 智慧自動化",
        "parent": "自動化與機器人",
        "primary_valuation": "forward_pe",
        "secondary_valuation": ["orders", "gross_margin", "cycle_position", "customer_validation"],
        "valuation_focus": ["Forward P/E", "訂單", "毛利率", "景氣循環", "機器視覺/傳動/控制"],
        "base_pe": 32, "pe_range": (22, 58), "base_pb": None, "pb_range": None,
        "cyclical": True, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": True, "liquidity_sensitive": True,
        "operable_discount_factor": 0.90,
        "risk_flags": ["工具機循環", "題材未落地", "訂單遞延", "中國景氣"],
        "note": "機器人需分成熟設備與 AI 機器人題材；題材未落地者要折價。",
    },
    "SPACE_LEO_SATELLITE": {
        "display_name": "太空科技 / 低軌衛星 / 無人載具",
        "parent": "太空科技與航太",
        "primary_valuation": "forward_pe_or_event",
        "secondary_valuation": ["orders", "customer_validation", "gross_margin", "event_milestone"],
        "valuation_focus": ["Forward P/E", "訂單", "客戶認證", "地面終端", "RF/毫米波", "事件里程碑"],
        "base_pe": 36, "pe_range": (25, 65), "base_pb": None, "pb_range": None,
        "cyclical": False, "pe_applicable": "conditional", "pe_trap_warning": True,
        "theme_premium_allowed": True, "liquidity_sensitive": True,
        "operable_discount_factor": 0.82,
        "risk_flags": ["題材先漲", "訂單未確認", "政策事件", "籌碼急轉", "EPS 未落地"],
        "note": "有實質訂單可用 Forward P/E；純概念股應轉入題材/事件模型。",
    },
    "EV_AUTO_ELECTRONICS": {
        "display_name": "車用電子 / 電動車零組件",
        "parent": "車用電子與電動車",
        "primary_valuation": "forward_pe",
        "secondary_valuation": ["certification_cycle", "orders", "gross_margin", "revenue_growth"],
        "valuation_focus": ["Forward P/E", "認證週期", "訂單穩定度", "毛利率", "車用占比"],
        "base_pe": 32, "pe_range": (24, 55), "base_pb": None, "pb_range": None,
        "cyclical": False, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": True, "liquidity_sensitive": True,
        "operable_discount_factor": 0.92,
        "risk_flags": ["車廠庫存", "認證延遲", "價格競爭", "EV 需求波動"],
        "note": "車用電子認證期長、訂單黏著度高，估值邏輯不同於消費電子。",
    },
    "GRID_POWER_STORAGE": {
        "display_name": "重電 / 電網 / 儲能",
        "parent": "電力基建與能源",
        "primary_valuation": "forward_pe_orders",
        "secondary_valuation": ["order_backlog", "policy_spending", "gross_margin", "cash_flow"],
        "valuation_focus": ["Forward P/E", "訂單能見度", "台電/海外標案", "毛利率", "現金流"],
        "base_pe": 34, "pe_range": (24, 50), "base_pb": None, "pb_range": None,
        "cyclical": False, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": True, "liquidity_sensitive": True,
        "operable_discount_factor": 0.90,
        "risk_flags": ["政策標案時程", "交貨認列", "原物料成本", "漲多估值修正"],
        "note": "重電與工具機不可混用；重電可享長單與基建溢價。",
    },
    "SOFTWARE_SECURITY_CLOUD": {
        "display_name": "軟體 / 資安 / 雲端 / 系統整合",
        "parent": "軟體與資訊服務",
        "primary_valuation": "pe_fcf_growth",
        "secondary_valuation": ["revenue_growth", "gross_margin", "fcf", "recurring_revenue"],
        "valuation_focus": ["P/E", "營收成長", "毛利率", "FCF", "經常性收入"],
        "base_pe": 34, "pe_range": (24, 55), "base_pb": None, "pb_range": None,
        "cyclical": False, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": False, "liquidity_sensitive": True,
        "operable_discount_factor": 0.92,
        "risk_flags": ["專案認列遞延", "人力成本", "政府標案時程", "AI 題材未落地"],
        "note": "有穩定獲利者可用 P/E；純 AI 軟體題材不給獨立高倍率。",
    },
    "MEMORY_CYCLE": {
        "display_name": "記憶體 / DRAM / NAND / 模組",
        "parent": "循環電子",
        "primary_valuation": "pb_cycle",
        "secondary_valuation": ["spot_price", "inventory_cycle", "revenue_growth", "gross_margin"],
        "valuation_focus": ["P/B", "報價循環", "庫存週期", "月營收", "毛利率"],
        "base_pe": None, "pe_range": None, "base_pb": 1.2, "pb_range": (0.7, 2.5),
        "cyclical": True, "pe_applicable": "secondary_only", "pe_trap_warning": True,
        "theme_premium_allowed": False, "liquidity_sensitive": True,
        "operable_discount_factor": 0.86,
        "risk_flags": ["景氣高峰低 P/E 陷阱", "庫存修正", "報價下跌", "P/E 失真"],
        "note": "記憶體需優先用 P/B 與報價循環，低 P/E 不一定代表低估。",
    },
    "DISPLAY_LED_CYCLE": {
        "display_name": "面板 / LED / 光電循環",
        "parent": "循環電子",
        "primary_valuation": "pb_cycle",
        "secondary_valuation": ["panel_price", "utilization", "revenue_growth"],
        "valuation_focus": ["P/B", "報價循環", "產能利用率", "月營收"],
        "base_pe": None, "pe_range": None, "base_pb": 0.9, "pb_range": (0.5, 1.8),
        "cyclical": True, "pe_applicable": "secondary_only", "pe_trap_warning": True,
        "theme_premium_allowed": False, "liquidity_sensitive": True,
        "operable_discount_factor": 0.84,
        "risk_flags": ["面板報價反轉", "產能過剩", "P/E 失真", "景氣高峰低 P/E 陷阱"],
        "note": "面板/LED 與高階光學鏡頭必須分開估值。",
    },
    "PASSIVE_COMPONENT_CYCLE": {
        "display_name": "被動元件 / 電容電阻電感",
        "parent": "循環電子",
        "primary_valuation": "pb_cycle",
        "secondary_valuation": ["pricing_cycle", "inventory", "revenue_growth", "gross_margin"],
        "valuation_focus": ["P/B", "報價循環", "庫存", "毛利率", "月營收"],
        "base_pe": None, "pe_range": None, "base_pb": 1.6, "pb_range": (0.8, 3.0),
        "cyclical": True, "pe_applicable": "secondary_only", "pe_trap_warning": True,
        "theme_premium_allowed": False, "liquidity_sensitive": True,
        "operable_discount_factor": 0.86,
        "risk_flags": ["庫存修正", "報價下跌", "景氣高峰低 P/E 陷阱", "需求轉弱"],
        "note": "被動元件需看庫存與報價，P/E 只能輔助。",
    },
    "FINANCIAL": {
        "display_name": "金融 / 金控 / 銀行 / 保險",
        "parent": "金融",
        "primary_valuation": "pb_roe_dividend",
        "secondary_valuation": ["roe", "dividend_yield", "capital_adequacy"],
        "valuation_focus": ["P/B", "ROE", "殖利率", "資本適足率", "利率循環"],
        "base_pe": None, "pe_range": None, "base_pb": 1.2, "pb_range": (0.8, 2.0),
        "cyclical": True, "pe_applicable": "secondary_only", "pe_trap_warning": True,
        "theme_premium_allowed": False, "liquidity_sensitive": False,
        "operable_discount_factor": 0.95,
        "risk_flags": ["利率循環", "保險匯損", "資產品質", "P/E 不適合作為主估值"],
        "note": "金融以 P/B 與 ROE 為主，不應使用科技股 P/E Cap。",
    },
    "TRADITIONAL_CYCLE": {
        "display_name": "傳產循環 / 原物料 / 化工 / 鋼鐵",
        "parent": "非電子循環",
        "primary_valuation": "pb_cycle",
        "secondary_valuation": ["spread_cycle", "cash_flow", "dividend_yield"],
        "valuation_focus": ["P/B", "產品利差", "景氣循環", "現金流", "殖利率"],
        "base_pe": None, "pe_range": None, "base_pb": 1.1, "pb_range": (0.6, 2.2),
        "cyclical": True, "pe_applicable": "secondary_only", "pe_trap_warning": True,
        "theme_premium_allowed": False, "liquidity_sensitive": True,
        "operable_discount_factor": 0.88,
        "risk_flags": ["景氣高峰低 P/E 陷阱", "原物料利差反轉", "需求循環", "現金流波動"],
        "note": "傳產循環優先看 P/B、利差與景氣位置。",
    },
    "SHIPPING_CYCLE": {
        "display_name": "航運 / 空運 / 物流循環",
        "parent": "非電子循環",
        "primary_valuation": "pb_cycle_freight",
        "secondary_valuation": ["freight_rate", "dividend_yield", "cash_flow"],
        "valuation_focus": ["P/B", "運價", "景氣循環", "殖利率", "現金流"],
        "base_pe": None, "pe_range": None, "base_pb": 1.0, "pb_range": (0.5, 2.0),
        "cyclical": True, "pe_applicable": "secondary_only", "pe_trap_warning": True,
        "theme_premium_allowed": False, "liquidity_sensitive": True,
        "operable_discount_factor": 0.82,
        "risk_flags": ["景氣高峰低 P/E 陷阱", "運價反轉", "高殖利率不可持續", "景氣急轉"],
        "note": "航運不應硬套 P/E；需以 P/B 與運價週期為主。",
    },
    "BIOTECH_MEDICAL": {
        "display_name": "生技醫療 / 藥廠 / 醫材",
        "parent": "生技醫療",
        "primary_valuation": "pe_or_milestone",
        "secondary_valuation": ["gross_margin", "pipeline", "cash_flow", "regulatory_milestones"],
        "valuation_focus": ["P/E", "毛利率", "研發里程碑", "現金流", "法規進度"],
        "base_pe": 35, "pe_range": (20, 65), "base_pb": None, "pb_range": None,
        "cyclical": False, "pe_applicable": "conditional", "pe_trap_warning": True,
        "theme_premium_allowed": True, "liquidity_sensitive": True,
        "operable_discount_factor": 0.82,
        "risk_flags": ["新藥里程碑失敗", "法規風險", "現金流不足", "EPS 不穩"],
        "note": "成熟藥廠可用 P/E，新藥題材應以里程碑與現金流評估。",
    },
    "CONSUMER_TOURISM": {
        "display_name": "消費 / 觀光 / 生活產業",
        "parent": "消費服務",
        "primary_valuation": "pe_cashflow",
        "secondary_valuation": ["same_store_sales", "expansion", "dividend_yield", "cash_flow"],
        "valuation_focus": ["P/E", "現金流", "展店", "同店成長", "殖利率"],
        "base_pe": 24, "pe_range": (15, 42), "base_pb": None, "pb_range": None,
        "cyclical": False, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": False, "liquidity_sensitive": True,
        "operable_discount_factor": 0.92,
        "risk_flags": ["消費景氣", "展店不如預期", "成本上升", "人力成本"],
        "note": "消費與觀光以現金流、展店與同店成長為主。",
    },
    "THEME_EVENT": {
        "display_name": "題材 / 事件驅動股",
        "parent": "特殊題材",
        "primary_valuation": "event_chip",
        "secondary_valuation": ["orders", "catalysts", "volume", "financial_delivery"],
        "valuation_focus": ["事件催化", "訂單真實性", "籌碼", "成交量", "財報落地程度"],
        "base_pe": None, "pe_range": None, "base_pb": None, "pb_range": None,
        "cyclical": False, "pe_applicable": False, "pe_trap_warning": True,
        "theme_premium_allowed": False, "liquidity_sensitive": True,
        "operable_discount_factor": 0.60,
        "risk_flags": ["EPS 未支撐", "法人目標不足", "籌碼急轉", "消息鈍化", "不適合一般 P/E 買進模型"],
        "note": "題材股不輸出 P/E 買進倍率；只可作事件與籌碼風險提示。",
    },
    "GENERAL": {
        "display_name": "一般產業 / 尚未分類",
        "parent": "未分類",
        "primary_valuation": "pe_pb_crosscheck",
        "secondary_valuation": ["roe", "revenue_growth", "fcf"],
        "valuation_focus": ["P/E", "P/B", "ROE", "月營收", "FCF"],
        "base_pe": 25, "pe_range": (15, 40), "base_pb": None, "pb_range": None,
        "cyclical": False, "pe_applicable": True, "pe_trap_warning": False,
        "theme_premium_allowed": False, "liquidity_sensitive": True,
        "operable_discount_factor": 0.95,
        "risk_flags": ["分類不足", "資料不足", "AI/系統分歧"],
        "note": "通用模型；建議人工確認產業後再提高可信度。",
    },
}


def get_taxonomy(taxon_key: str):
    """安全取得產業分類設定。"""
    if not taxon_key:
        return INDUSTRY_TAXONOMY["GENERAL"]
    return INDUSTRY_TAXONOMY.get(str(taxon_key).strip().upper(), INDUSTRY_TAXONOMY["GENERAL"])
