"""
台股股票 → 產業估值模型對應表（第 17-C 全股票分類稽核修正版）。

原則：
- primary_taxon 決定主要估值模型。
- themes 只作題材標籤，不應取代主產業分類。
- 低軌衛星、車用、機器人、AI PC 等多數情況先作 theme，除非公司本業即為該主產業。
"""

STOCK_MAPPING = {'1319': {'name': '東陽', 'primary_taxon': 'AUTO_PARTS_AM', 'themes': ['AM汽車零件', '車用零件']},
 '1503': {'name': '士電', 'primary_taxon': 'GRID_POWER_STORAGE', 'themes': ['重電', '電網']},
 '1513': {'name': '中興電', 'primary_taxon': 'GRID_POWER_STORAGE', 'themes': ['重電', '電網']},
 '1514': {'name': '亞力', 'primary_taxon': 'GRID_POWER_STORAGE', 'themes': ['重電', '電網']},
 '1519': {'name': '華城', 'primary_taxon': 'GRID_POWER_STORAGE', 'themes': ['重電', '電網']},
 '1522': {'name': '堤維西', 'primary_taxon': 'AUTO_PARTS_AM', 'themes': ['車燈', 'AM汽車零件']},
 '1536': {'name': '和大', 'primary_taxon': 'AUTO_PARTS_EV', 'themes': ['傳動系統', 'EV零組件', '車用零件']},
 '1560': {'name': '中砂', 'primary_taxon': 'SEMICONDUCTOR_MATERIALS_CONSUMABLES', 'themes': ['半導體材料', '再生晶圓', '耗材', '先進製程']},
 '1590': {'name': '亞德客-KY', 'primary_taxon': 'ROBOTICS_AUTOMATION', 'themes': ['氣動元件', '自動化']},
 '1701': {'name': '中化', 'primary_taxon': 'BIOTECH_MEDICAL', 'themes': ['藥廠']},
 '1717': {'name': '長興', 'primary_taxon': 'SPECIALTY_CHEM_ELECTRONIC_MATERIALS', 'themes': ['特用化學', '電子材料', 'PCB材料', '樹脂', '光電材料']},
 '1795': {'name': '美時', 'primary_taxon': 'BIOTECH_MEDICAL', 'themes': ['學名藥']},
 '2049': {'name': '上銀', 'primary_taxon': 'ROBOTICS_AUTOMATION', 'themes': ['傳動', '機器人']},
 '2059': {'name': '川湖', 'primary_taxon': 'SERVER_CHASSIS_RAIL', 'themes': ['滑軌', '伺服器']},
 '2201': {'name': '裕隆', 'primary_taxon': 'AUTO_OEM_CYCLE', 'themes': ['整車', '汽車集團', '資產']},
 '2231': {'name': '為升', 'primary_taxon': 'EV_AUTO_ELECTRONICS', 'themes': ['車用電子']},
 '2301': {'name': '光寶科', 'primary_taxon': 'POWER_BBU', 'themes': ['電源', 'AI伺服器']},
 '2303': {'name': '聯電', 'primary_taxon': 'FOUNDRY', 'themes': ['成熟製程', '車用', '工控']},
 '2308': {'name': '台達電', 'primary_taxon': 'POWER_BBU', 'themes': ['電源', 'BBU', '資料中心', '電動車']},
 '2313': {'name': '華通', 'primary_taxon': 'SERVER_PCB_BOARD', 'themes': ['PCB', '高階板', '低軌衛星']},
 '2314': {'name': '台揚', 'primary_taxon': 'SPACE_LEO_SATELLITE', 'themes': ['低軌衛星', '通訊']},
 '2317': {'name': '鴻海', 'primary_taxon': 'AI_SERVER_ODM', 'themes': ['AI伺服器', '電動車']},
 '2324': {'name': '仁寶', 'primary_taxon': 'PC_NB_ODM', 'themes': ['NB ODM', 'PC代工', 'AI PC']},
 '2330': {'name': '台積電', 'primary_taxon': 'FOUNDRY', 'themes': ['AI', 'HPC', 'CoWoS', '先進製程']},
 '2344': {'name': '華邦電', 'primary_taxon': 'MEMORY_CYCLE', 'themes': ['DRAM', '記憶體循環']},
 '2345': {'name': '智邦', 'primary_taxon': 'NETWORK_SWITCH', 'themes': ['AI交換器', '網通']},
 '2351': {'name': '順德', 'primary_taxon': 'SEMICONDUCTOR_MATERIALS_CONSUMABLES', 'themes': ['導線架', '功率元件材料', '車用半導體材料']},
 '2353': {'name': '宏碁', 'primary_taxon': 'PC_BRAND_AI_PC', 'themes': ['PC品牌', 'AI PC']},
 '2356': {'name': '英業達', 'primary_taxon': 'AI_SERVER_ODM', 'themes': ['AI伺服器']},
 '2357': {'name': '華碩', 'primary_taxon': 'PC_BRAND_AI_PC', 'themes': ['PC品牌', '主板', 'AI PC', '伺服器系統']},
 '2359': {'name': '所羅門', 'primary_taxon': 'ROBOTICS_AUTOMATION', 'themes': ['機器人', 'AI視覺']},
 '2360': {'name': '致茂', 'primary_taxon': 'TEST_AUTOMATION_EQUIPMENT', 'themes': ['測試設備', '自動化測試', '電源測試']},
 '2367': {'name': '燿華', 'primary_taxon': 'SERVER_PCB_BOARD', 'themes': ['PCB', '車用']},
 '2368': {'name': '金像電', 'primary_taxon': 'SERVER_PCB_BOARD', 'themes': ['AI伺服器主板', 'PCB']},
 '2371': {'name': '大同', 'primary_taxon': 'GRID_POWER_STORAGE', 'themes': ['重電', '電網', '機器人題材']},
 '2376': {'name': '技嘉', 'primary_taxon': 'AI_SERVER_BOARD_SYSTEM', 'themes': ['主板', 'GPU', 'AI伺服器系統']},
 '2377': {'name': '微星', 'primary_taxon': 'AI_SERVER_BOARD_SYSTEM', 'themes': ['主板', 'GPU', 'AI伺服器系統']},
 '2382': {'name': '廣達', 'primary_taxon': 'AI_SERVER_ODM', 'themes': ['AI伺服器', 'ODM']},
 '2383': {'name': '台光電', 'primary_taxon': 'CCL_HIGH_SPEED_MATERIALS', 'themes': ['CCL', '高速材料', 'AI伺服器', '高階PCB材料']},
 '2388': {'name': '威盛', 'primary_taxon': 'IC_DESIGN_ASIC', 'themes': ['AI邊緣運算', '車用']},
 '2392': {'name': '正崴', 'primary_taxon': 'CONNECTOR_CABLE', 'themes': ['連接器', '電源']},
 '2404': {'name': '漢唐', 'primary_taxon': 'FAB_FACILITY_MATERIALS', 'themes': ['廠務', '無塵室']},
 '2408': {'name': '南亞科', 'primary_taxon': 'MEMORY_CYCLE', 'themes': ['DRAM', '記憶體循環']},
 '2421': {'name': '建準', 'primary_taxon': 'THERMAL_LIQUID_COOLING', 'themes': ['散熱風扇']},
 '2449': {'name': '京元電子', 'primary_taxon': 'OSAT_TESTING', 'themes': ['測試', 'AI晶片測試']},
 '2451': {'name': '創見', 'primary_taxon': 'MEMORY_CYCLE', 'themes': ['記憶體模組']},
 '2453': {'name': '凌群', 'primary_taxon': 'SOFTWARE_SECURITY_CLOUD', 'themes': ['系統整合']},
 '2454': {'name': '聯發科', 'primary_taxon': 'IC_DESIGN_ASIC', 'themes': ['AI ASIC', '手機晶片', '車用電子']},
 '2464': {'name': '盟立', 'primary_taxon': 'ROBOTICS_AUTOMATION', 'themes': ['自動化']},
 '2467': {'name': '志聖', 'primary_taxon': 'SEMICAP_COWOS_EQUIPMENT', 'themes': ['設備', 'PCB設備']},
 '2480': {'name': '敦陽科', 'primary_taxon': 'SOFTWARE_SECURITY_CLOUD', 'themes': ['系統整合']},
 '2486': {'name': '一詮', 'primary_taxon': 'THERMAL_LIQUID_COOLING', 'themes': ['散熱零件']},
 '2603': {'name': '長榮', 'primary_taxon': 'SHIPPING_CYCLE', 'themes': ['海運']},
 '2609': {'name': '陽明', 'primary_taxon': 'SHIPPING_CYCLE', 'themes': ['海運']},
 '2615': {'name': '萬海', 'primary_taxon': 'SHIPPING_CYCLE', 'themes': ['海運']},
 '2881': {'name': '富邦金', 'primary_taxon': 'FINANCIAL', 'themes': ['金控']},
 '2891': {'name': '中信金', 'primary_taxon': 'FINANCIAL', 'themes': ['金控']},
 '3008': {'name': '大立光', 'primary_taxon': 'OPTICS_LENS_MODULE', 'themes': ['手機鏡頭', 'AI光學', '車用鏡頭']},
 '3013': {'name': '晟銘電', 'primary_taxon': 'SERVER_CHASSIS_RAIL', 'themes': ['機殼']},
 '3015': {'name': '全漢', 'primary_taxon': 'POWER_BBU', 'themes': ['電源']},
 '3017': {'name': '奇鋐', 'primary_taxon': 'THERMAL_LIQUID_COOLING', 'themes': ['AI散熱', '水冷']},
 '3019': {'name': '亞光', 'primary_taxon': 'OPTICS_LENS_MODULE', 'themes': ['光學模組', '車用光學']},
 '3025': {'name': '星通', 'primary_taxon': 'NETWORK_SWITCH', 'themes': ['網通']},
 '3029': {'name': '零壹', 'primary_taxon': 'SOFTWARE_SECURITY_CLOUD', 'themes': ['資安', '雲端']},
 '3035': {'name': '智原', 'primary_taxon': 'IC_DESIGN_ASIC', 'themes': ['ASIC', '設計服務']},
 '3037': {'name': '欣興', 'primary_taxon': 'ABF_SUBSTRATE', 'themes': ['AI載板', 'HPC', 'ABF']},
 '3044': {'name': '健鼎', 'primary_taxon': 'SERVER_PCB_BOARD', 'themes': ['PCB', '伺服器']},
 '3078': {'name': '僑威', 'primary_taxon': 'POWER_BBU', 'themes': ['電源']},
 '3081': {'name': '聯亞', 'primary_taxon': 'OPTICAL_COMM_SILICON_PHOTONICS', 'themes': ['光通訊']},
 '3131': {'name': '弘塑', 'primary_taxon': 'SEMICAP_COWOS_EQUIPMENT', 'themes': ['CoWoS', '濕製程']},
 '3163': {'name': '波若威', 'primary_taxon': 'OPTICAL_COMM_SILICON_PHOTONICS', 'themes': ['光通訊']},
 '3189': {'name': '景碩', 'primary_taxon': 'ABF_SUBSTRATE', 'themes': ['ABF', '載板']},
 '3231': {'name': '緯創', 'primary_taxon': 'AI_SERVER_ODM', 'themes': ['AI伺服器', 'ODM']},
 '3260': {'name': '威剛', 'primary_taxon': 'MEMORY_CYCLE', 'themes': ['記憶體模組']},
 '3264': {'name': '欣銓', 'primary_taxon': 'OSAT_TESTING', 'themes': ['測試', '車用']},
 '3324': {'name': '雙鴻', 'primary_taxon': 'THERMAL_LIQUID_COOLING', 'themes': ['AI散熱', '水冷']},
 '3338': {'name': '泰碩', 'primary_taxon': 'THERMAL_LIQUID_COOLING', 'themes': ['散熱']},
 '3362': {'name': '先進光', 'primary_taxon': 'OPTICS_LENS_MODULE', 'themes': ['光學鏡頭']},
 '3363': {'name': '上詮', 'primary_taxon': 'OPTICAL_COMM_SILICON_PHOTONICS', 'themes': ['光通訊']},
 '3380': {'name': '明泰', 'primary_taxon': 'NETWORK_SWITCH', 'themes': ['網通', '低軌衛星']},
 '3406': {'name': '玉晶光', 'primary_taxon': 'OPTICS_LENS_MODULE', 'themes': ['手機鏡頭', '光學']},
 '3443': {'name': '創意', 'primary_taxon': 'IC_DESIGN_ASIC', 'themes': ['ASIC', '設計服務', 'HPC']},
 '3450': {'name': '聯鈞', 'primary_taxon': 'OPTICAL_COMM_SILICON_PHOTONICS', 'themes': ['光通訊']},
 '3455': {'name': '由田', 'primary_taxon': 'TEST_AUTOMATION_EQUIPMENT', 'themes': ['AOI', '檢測設備', 'PCB/半導體檢測']},
 '3483': {'name': '力致', 'primary_taxon': 'THERMAL_LIQUID_COOLING', 'themes': ['散熱']},
 '3491': {'name': '昇達科', 'primary_taxon': 'SPACE_LEO_SATELLITE', 'themes': ['毫米波', '低軌衛星']},
 '3529': {'name': '力旺', 'primary_taxon': 'IP_EDA_DESIGN_SERVICE', 'themes': ['矽智財', 'IP授權']},
 '3533': {'name': '嘉澤', 'primary_taxon': 'CONNECTOR_CABLE', 'themes': ['高速連接器', 'AI伺服器']},
 '3552': {'name': '同致', 'primary_taxon': 'EV_AUTO_ELECTRONICS', 'themes': ['ADAS', '車用電子']},
 '3583': {'name': '辛耘', 'primary_taxon': 'SEMICAP_COWOS_EQUIPMENT', 'themes': ['CoWoS', '半導體設備']},
 '3596': {'name': '智易', 'primary_taxon': 'NETWORK_SWITCH', 'themes': ['網通']},
 '3605': {'name': '宏致', 'primary_taxon': 'CONNECTOR_CABLE', 'themes': ['連接器']},
 '3630': {'name': '新鉅科', 'primary_taxon': 'OPTICS_LENS_MODULE', 'themes': ['光學鏡頭']},
 '3653': {'name': '健策', 'primary_taxon': 'THERMAL_LIQUID_COOLING', 'themes': ['均熱片', '散熱']},
 '3661': {'name': '世芯-KY', 'primary_taxon': 'IC_DESIGN_ASIC', 'themes': ['AI ASIC', 'HPC', '客製化晶片']},
 '3665': {'name': '貿聯-KY', 'primary_taxon': 'CONNECTOR_CABLE', 'themes': ['高速傳輸', '車用電子', 'AI伺服器']},
 '3680': {'name': '家登', 'primary_taxon': 'SEMICONDUCTOR_MATERIALS_CONSUMABLES', 'themes': ['EUV', '晶圓載具', '半導體耗材']},
 '3693': {'name': '營邦', 'primary_taxon': 'SERVER_CHASSIS_RAIL', 'themes': ['伺服器機殼']},
 '3704': {'name': '合勤控', 'primary_taxon': 'NETWORK_SWITCH', 'themes': ['網通', '通訊']},
 '3706': {'name': '神達', 'primary_taxon': 'AI_SERVER_ODM', 'themes': ['AI伺服器']},
 '3708': {'name': '上緯投控', 'primary_taxon': 'GREEN_ENERGY_INFRA', 'themes': ['風電材料', '綠能', '風電']},
 '3711': {'name': '日月光投控', 'primary_taxon': 'OSAT_TESTING', 'themes': ['先進封裝', '封測']},
 '3715': {'name': '定穎投控', 'primary_taxon': 'SERVER_PCB_BOARD', 'themes': ['PCB', '車用']},
 '4105': {'name': '東洋', 'primary_taxon': 'BIOTECH_MEDICAL', 'themes': ['藥廠']},
 '4128': {'name': '中裕', 'primary_taxon': 'BIOTECH_MEDICAL', 'themes': ['新藥']},
 '4510': {'name': '高鋒', 'primary_taxon': 'MACHINE_TOOL_CYCLE', 'themes': ['工具機']},
 '4526': {'name': '東台', 'primary_taxon': 'MACHINE_TOOL_CYCLE', 'themes': ['工具機', '自動化']},
 '4543': {'name': '萬在', 'primary_taxon': 'THERMAL_LIQUID_COOLING', 'themes': ['散熱']},
 '4743': {'name': '合一', 'primary_taxon': 'BIOTECH_MEDICAL', 'themes': ['新藥']},
 '4906': {'name': '正文', 'primary_taxon': 'NETWORK_SWITCH', 'themes': ['網通']},
 '4908': {'name': '前鼎', 'primary_taxon': 'OPTICAL_COMM_SILICON_PHOTONICS', 'themes': ['光通訊']},
 '4938': {'name': '和碩', 'primary_taxon': 'PC_NB_ODM', 'themes': ['ODM', 'EMS', 'PC/NB代工']},
 '4953': {'name': '緯軟', 'primary_taxon': 'SOFTWARE_SECURITY_CLOUD', 'themes': ['軟體服務']},
 '4966': {'name': '譜瑞-KY', 'primary_taxon': 'IC_DESIGN_ASIC', 'themes': ['高速介面', 'ASIC']},
 '4967': {'name': '十銓', 'primary_taxon': 'MEMORY_CYCLE', 'themes': ['記憶體模組']},
 '4976': {'name': '佳凌', 'primary_taxon': 'OPTICS_LENS_MODULE', 'themes': ['光學鏡頭']},
 '4977': {'name': '眾達-KY', 'primary_taxon': 'OPTICAL_COMM_SILICON_PHOTONICS', 'themes': ['光通訊']},
 '4979': {'name': '華星光', 'primary_taxon': 'OPTICAL_COMM_SILICON_PHOTONICS', 'themes': ['光通訊']},
 '5212': {'name': '凌網', 'primary_taxon': 'SOFTWARE_SECURITY_CLOUD', 'themes': ['資訊服務']},
 '5269': {'name': '祥碩', 'primary_taxon': 'IC_DESIGN_ASIC', 'themes': ['高速傳輸', 'IC設計']},
 '5274': {'name': '信驊', 'primary_taxon': 'IC_DESIGN_ASIC', 'themes': ['伺服器BMC', '資料中心']},
 '5388': {'name': '中磊', 'primary_taxon': 'NETWORK_SWITCH', 'themes': ['網通']},
 '5426': {'name': '振發', 'primary_taxon': 'SERVER_CHASSIS_RAIL', 'themes': ['機殼', '工業電腦機構件']},
 '5443': {'name': '均豪', 'primary_taxon': 'TEST_AUTOMATION_EQUIPMENT', 'themes': ['AOI', '設備', '自動化檢測']},
 '6112': {'name': '邁達特', 'primary_taxon': 'SOFTWARE_SECURITY_CLOUD', 'themes': ['系統整合']},
 '6117': {'name': '迎廣', 'primary_taxon': 'SERVER_CHASSIS_RAIL', 'themes': ['機殼']},
 '6125': {'name': '廣運', 'primary_taxon': 'ROBOTICS_AUTOMATION', 'themes': ['自動化', '物流設備', '散熱題材待確認']},
 '6139': {'name': '亞翔', 'primary_taxon': 'FAB_FACILITY_MATERIALS', 'themes': ['廠務', '無塵室']},
 '6187': {'name': '萬潤', 'primary_taxon': 'SEMICAP_COWOS_EQUIPMENT', 'themes': ['CoWoS', '設備']},
 '6188': {'name': '廣明', 'primary_taxon': 'ROBOTICS_AUTOMATION', 'themes': ['機器人題材', '自動化']},
 '6196': {'name': '帆宣', 'primary_taxon': 'FAB_FACILITY_MATERIALS', 'themes': ['廠務', '半導體工程']},
 '6197': {'name': '佳必琪', 'primary_taxon': 'CONNECTOR_CABLE', 'themes': ['高速連接', '線材']},
 '6209': {'name': '今國光', 'primary_taxon': 'OPTICS_LENS_MODULE', 'themes': ['光學鏡頭']},
 '6213': {'name': '聯茂', 'primary_taxon': 'CCL_HIGH_SPEED_MATERIALS', 'themes': ['CCL', '銅箔基板', 'PCB材料', '高階材料']},
 '6214': {'name': '精誠', 'primary_taxon': 'SOFTWARE_SECURITY_CLOUD', 'themes': ['系統整合', '資安']},
 '6223': {'name': '旺矽', 'primary_taxon': 'PROBE_TEST_INTERFACE', 'themes': ['探針卡', '測試介面']},
 '6230': {'name': '尼得科超眾', 'primary_taxon': 'THERMAL_LIQUID_COOLING', 'themes': ['散熱']},
 '6257': {'name': '矽格', 'primary_taxon': 'OSAT_TESTING', 'themes': ['封測', '測試']},
 '6271': {'name': '同欣電', 'primary_taxon': 'RF_MODULE_PACKAGING', 'themes': ['RF封裝', '車用', '特殊封裝']},
 '6274': {'name': '台燿', 'primary_taxon': 'CCL_HIGH_SPEED_MATERIALS', 'themes': ['CCL', '高速材料', 'AI伺服器', '高階PCB材料']},
 '6275': {'name': '元山', 'primary_taxon': 'THERMAL_LIQUID_COOLING', 'themes': ['風扇', '散熱']},
 '6282': {'name': '康舒', 'primary_taxon': 'POWER_BBU', 'themes': ['電源']},
 '6285': {'name': '啟碁', 'primary_taxon': 'NETWORK_SWITCH', 'themes': ['低軌衛星', '網通', '通訊設備']},
 '6290': {'name': '良維', 'primary_taxon': 'CONNECTOR_CABLE', 'themes': ['線材', '電源線']},
 '6412': {'name': '群電', 'primary_taxon': 'POWER_BBU', 'themes': ['電源']},
 '6438': {'name': '迅得', 'primary_taxon': 'SEMICAP_COWOS_EQUIPMENT', 'themes': ['自動化', '半導體設備']},
 '6442': {'name': '光聖', 'primary_taxon': 'OPTICAL_COMM_SILICON_PHOTONICS', 'themes': ['光通訊', '矽光子']},
 '6451': {'name': '訊芯-KY', 'primary_taxon': 'OPTICAL_COMM_SILICON_PHOTONICS', 'themes': ['矽光子', '封裝']},
 '6462': {'name': '神盾', 'primary_taxon': 'IC_DESIGN_ASIC', 'themes': ['邊緣AI', '感測']},
 '6472': {'name': '保瑞', 'primary_taxon': 'BIOTECH_MEDICAL', 'themes': ['藥廠', 'CDMO']},
 '6510': {'name': '精測', 'primary_taxon': 'PROBE_TEST_INTERFACE', 'themes': ['探針卡', '測試介面']},
 '6515': {'name': '穎崴', 'primary_taxon': 'PROBE_TEST_INTERFACE', 'themes': ['測試介面', 'AI晶片測試']},
 '6530': {'name': '創威', 'primary_taxon': 'OPTICAL_COMM_SILICON_PHOTONICS', 'themes': ['光通訊']},
 '6531': {'name': '愛普*', 'primary_taxon': 'IC_DESIGN_ASIC', 'themes': ['記憶體IP', 'AI記憶體']},
 '6533': {'name': '晶心科', 'primary_taxon': 'IP_EDA_DESIGN_SERVICE', 'themes': ['RISC-V', 'IP']},
 '6584': {'name': '南俊國際', 'primary_taxon': 'SERVER_CHASSIS_RAIL', 'themes': ['滑軌']},
 '6589': {'name': '台康生技', 'primary_taxon': 'BIOTECH_MEDICAL', 'themes': ['生物相似藥']},
 '6591': {'name': '動力-KY', 'primary_taxon': 'THERMAL_LIQUID_COOLING', 'themes': ['風扇', '散熱']},
 '6640': {'name': '均華', 'primary_taxon': 'SEMICAP_COWOS_EQUIPMENT', 'themes': ['先進封裝設備']},
 '6643': {'name': 'M31', 'primary_taxon': 'IP_EDA_DESIGN_SERVICE', 'themes': ['矽智財', 'IP授權']},
 '6664': {'name': '群翊', 'primary_taxon': 'SEMICAP_COWOS_EQUIPMENT', 'themes': ['設備', 'PCB設備']},
 '6669': {'name': '緯穎', 'primary_taxon': 'AI_SERVER_ODM', 'themes': ['AI伺服器', '資料中心']},
 '6683': {'name': '雍智科技', 'primary_taxon': 'PROBE_TEST_INTERFACE', 'themes': ['測試介面']},
 '6689': {'name': '伊雲谷', 'primary_taxon': 'SOFTWARE_SECURITY_CLOUD', 'themes': ['雲端']},
 '6712': {'name': '長聖', 'primary_taxon': 'BIOTECH_MEDICAL', 'themes': ['細胞治療']},
 '6715': {'name': '嘉基', 'primary_taxon': 'CONNECTOR_CABLE', 'themes': ['高速連接器']},
 '6751': {'name': '智聯服務', 'primary_taxon': 'SOFTWARE_SECURITY_CLOUD', 'themes': ['資訊服務']},
 '6789': {'name': '采鈺', 'primary_taxon': 'CIS_SEMICONDUCTOR_OPTICS', 'themes': ['CIS', '影像感測', '半導體光學', '先進封裝']},
 '6805': {'name': '富世達', 'primary_taxon': 'SERVER_CHASSIS_RAIL', 'themes': ['伺服器滑軌', '機構件', '水冷/散熱題材']},
 '6806': {'name': '森崴能源', 'primary_taxon': 'GREEN_ENERGY_INFRA', 'themes': ['儲能', '綠能工程', '再生能源']},
 '6811': {'name': '宏碁資訊', 'primary_taxon': 'SOFTWARE_SECURITY_CLOUD', 'themes': ['雲端', '系統整合']},
 '7769': {'name': '鴻勁', 'primary_taxon': 'TEST_AUTOMATION_EQUIPMENT', 'themes': ['測試設備', 'AI晶片測試', '自動化測試']},
 '7822': {'name': '倍利科', 'primary_taxon': 'TEST_AUTOMATION_EQUIPMENT', 'themes': ['半導體檢測', '設備', 'AOI']},
 '8027': {'name': '鈦昇', 'primary_taxon': 'SEMICAP_COWOS_EQUIPMENT', 'themes': ['設備']},
 '8033': {'name': '雷虎', 'primary_taxon': 'THEME_EVENT', 'themes': ['軍工', '無人機', '題材']},
 '8039': {'name': '台虹', 'primary_taxon': 'SPECIALTY_CHEM_ELECTRONIC_MATERIALS', 'themes': ['軟板材料', 'FCCL', 'PCB材料', '電子材料']},
 '8046': {'name': '南電', 'primary_taxon': 'ABF_SUBSTRATE', 'themes': ['AI載板', 'HPC', 'ABF']},
 '8054': {'name': '安國', 'primary_taxon': 'IC_DESIGN_ASIC', 'themes': ['儲存控制', 'AI PC']},
 '8064': {'name': '東捷', 'primary_taxon': 'SEMICAP_COWOS_EQUIPMENT', 'themes': ['FOPLP', '玻璃基板', '先進封裝設備', 'Micro LED', '自動化設備']},
 '8078': {'name': '華寶', 'primary_taxon': 'GENERAL', 'themes': ['待確認', '舊資料保留']},
 '8103': {'name': '瀚荃', 'primary_taxon': 'CONNECTOR_CABLE', 'themes': ['連接器', '低軌衛星', '線材']},
 '8210': {'name': '勤誠', 'primary_taxon': 'SERVER_CHASSIS_RAIL', 'themes': ['AI機櫃', '伺服器機殼']},
 '8227': {'name': '巨有科技', 'primary_taxon': 'IC_DESIGN_ASIC', 'themes': ['ASIC', '設計服務']},
 '8299': {'name': '群聯', 'primary_taxon': 'MEMORY_CONTROLLER_CYCLE', 'themes': ['NAND控制IC', '記憶體', '儲存控制']},
 '8374': {'name': '羅昇', 'primary_taxon': 'ROBOTICS_AUTOMATION', 'themes': ['自動化']},
 '8996': {'name': '高力', 'primary_taxon': 'THERMAL_LIQUID_COOLING', 'themes': ['散熱', '熱交換']},
 '9958': {'name': '世紀鋼', 'primary_taxon': 'GREEN_ENERGY_INFRA', 'themes': ['風電', '鋼構', '綠能基建']}}
