"""
台股股票 -> 產業估值模型對應表。

原則：
- primary_taxon 決定主要估值模型。
- themes 只作題材標籤，不應取代主產業分類。
- 已分批補齊 stocklist 與官方上市/上櫃清單缺漏股；新增分類需同步維護 industry_taxonomy.py 與 dynamic_cap_model.py。
"""

STOCK_MAPPING = {'1319': {'name': '東陽', 'primary_taxon': 'AUTO_PARTS_AM', 'themes': ['AM汽車零件', '車用零件']},
 '1503': {'name': '士電', 'primary_taxon': 'GRID_EQUIPMENT_CORE', 'themes': ['重電', '電網', '配電設備']},
 '1513': {'name': '中興電', 'primary_taxon': 'GRID_EQUIPMENT_CORE', 'themes': ['重電', '電網', '儲能', '電力設備']},
 '1514': {'name': '亞力', 'primary_taxon': 'GRID_EQUIPMENT_CORE', 'themes': ['重電', '電網', '工程訂單']},
 '1519': {'name': '華城', 'primary_taxon': 'GRID_TRANSFORMER_HIGH_VISIBILITY', 'themes': ['重電', '變壓器', '電網', '高能見度訂單']},
 '1522': {'name': '堤維西', 'primary_taxon': 'AUTO_PARTS_AM', 'themes': ['車燈', 'AM汽車零件']},
 '1536': {'name': '和大', 'primary_taxon': 'AUTO_PARTS_EV', 'themes': ['傳動系統', 'EV零組件', '車用零件']},
 '1560': {'name': '中砂', 'primary_taxon': 'SEMIMAT_ADVANCED_CONSUMABLES', 'themes': ['半導體材料', '鑽石碟', '耗材', '先進製程']},
 '1590': {'name': '亞德客-KY', 'primary_taxon': 'INDUSTRIAL_AUTOMATION_CORE', 'themes': ['氣動元件', '自動化', '工業自動化']},
 '1701': {'name': '中化', 'primary_taxon': 'PHARMA_DEFENSIVE_GENERIC', 'themes': ['藥廠', '成熟製藥', '防禦型']},
 '1717': {'name': '長興', 'primary_taxon': 'SPECIALTY_CHEM_ELECTRONIC_MATERIALS', 'themes': ['特用化學', '電子材料', 'PCB材料', '樹脂', '光電材料']},
 '1795': {'name': '美時', 'primary_taxon': 'PHARMA_CDMO_PROFIT', 'themes': ['學名藥', '外銷藥廠', '獲利型生技']},
 '2049': {'name': '上銀', 'primary_taxon': 'INDUSTRIAL_AUTOMATION_CORE', 'themes': ['傳動', '線性滑軌', '機器人', '工業自動化']},
 '2059': {'name': '川湖', 'primary_taxon': 'SERVER_RAIL_HIGH_VISIBILITY', 'themes': ['滑軌', '伺服器', '高毛利機構件']},
 '2201': {'name': '裕隆', 'primary_taxon': 'AUTO_OEM_CYCLE', 'themes': ['整車', '汽車集團', '資產']},
 '2231': {'name': '為升', 'primary_taxon': 'EV_AUTO_ELECTRONICS', 'themes': ['車用電子']},
 '2301': {'name': '光寶科', 'primary_taxon': 'DATACENTER_POWER_LEADER', 'themes': ['電源', 'AI伺服器', '資料中心電源']},
 '2302': {'name': '麗正', 'primary_taxon': 'POWER_DISCRETE_COMPONENT_CYCLE', 'themes': ['功率半導體', '整流二極體', '分離式元件']},
 '2303': {'name': '聯電', 'primary_taxon': 'FOUNDRY_MATURE', 'themes': ['成熟製程', '車用', '工控']},
 '2308': {'name': '台達電', 'primary_taxon': 'DATACENTER_POWER_LEADER', 'themes': ['電源', 'BBU', '資料中心', '電動車', '電源龍頭']},
 '2313': {'hybrid_taxons': [{'reason': '低軌衛星為附加題材，主分類仍為 AI Server 高階 PCB。', 'taxon': 'SPACE_LEO_SATELLITE', 'weight': 0.05}],
          'name': '華通',
          'primary_taxon': 'AI_SERVER_PCB_HIGH_VISIBILITY',
          'themes': ['PCB', '高階板', '低軌衛星', 'AI伺服器PCB']},
 '2314': {'name': '台揚', 'primary_taxon': 'SPACE_LEO_SATELLITE', 'themes': ['低軌衛星', '通訊']},
 '2317': {'hybrid_taxons': [{'reason': 'AI server 占大型 EMS 平台成長動能比重提高，但仍保留 EMS 主體。', 'taxon': 'AI_SERVER_ODM', 'weight': 0.3},
                            {'reason': 'EV 為中長期成長曲線，維持低權重避免過度加分。', 'taxon': 'EV_AUTO_ELECTRONICS', 'weight': 0.05}],
          'name': '鴻海',
          'primary_taxon': 'EMS_PLATFORM_CONTRACT_MANUFACTURING',
          'themes': ['EMS', 'AI伺服器', '電動車', '消費電子']},
 '2324': {'hybrid_taxons': [{'reason': 'AI PC/伺服器題材仍屬初期，維持低權重。', 'taxon': 'AI_SERVER_ODM', 'weight': 0.08}],
          'name': '仁寶',
          'primary_taxon': 'PC_NB_ODM',
          'themes': ['NB ODM', 'AI PC', '伺服器題材']},
 '2327': {'name': '國巨', 'primary_taxon': 'PASSIVE_COMPONENT_CYCLE', 'themes': ['被動元件', 'MLCC', '電阻', '景氣循環']},
 '2329': {'name': '華泰', 'primary_taxon': 'MEMORY_OSAT_CYCLE', 'themes': ['記憶體封測', 'IC封裝', '封測循環']},
 '2330': {'name': '台積電', 'primary_taxon': 'FOUNDRY_ADVANCED', 'themes': ['AI', 'HPC', 'CoWoS', '先進製程']},
 '2337': {'name': '旺宏', 'primary_taxon': 'MEMORY_MANUFACTURING_CYCLE', 'themes': ['NOR Flash', '記憶體製造', 'Flash', 'P/B週期']},
 '2338': {'name': '光罩', 'primary_taxon': 'SEMIMAT_ADVANCED_CONSUMABLES', 'themes': ['光罩', 'Photomask', '半導體材料']},
 '2340': {'name': '台亞', 'primary_taxon': 'COMPOUND_SEMICONDUCTOR_OPTO', 'themes': ['化合物半導體', 'LED', '光電半導體']},
 '2342': {'name': '茂矽', 'primary_taxon': 'FOUNDRY_MATURE', 'themes': ['成熟製程', '晶圓代工', '記憶體循環']},
 '2344': {'name': '華邦電', 'primary_taxon': 'MEMORY_MANUFACTURING_CYCLE', 'themes': ['DRAM', '記憶體製造', 'P/B週期']},
 '2345': {'name': '智邦', 'primary_taxon': 'AI_DATACENTER_SWITCH', 'themes': ['AI交換器', '網通', '資料中心網路']},
 '2351': {'name': '順德', 'primary_taxon': 'SEMIMAT_POWER_LEADFRAME', 'themes': ['導線架', '功率元件材料', '車用半導體材料']},
 '2353': {'name': '宏碁', 'primary_taxon': 'PC_BRAND_AI_PC', 'themes': ['PC品牌', 'AI PC']},
 '2356': {'hybrid_taxons': [{'reason': 'AI/伺服器有貢獻，但純度低於廣達、緯創，權重小幅下修。', 'taxon': 'AI_SERVER_ODM', 'weight': 0.22}],
          'name': '英業達',
          'primary_taxon': 'PC_NB_ODM',
          'themes': ['NB ODM', '伺服器', 'AI伺服器']},
 '2357': {'name': '華碩', 'primary_taxon': 'PC_BRAND_AI_PC', 'themes': ['PC品牌', '主板', 'AI PC', '伺服器系統']},
 '2359': {'name': '所羅門', 'primary_taxon': 'ROBOTICS_THEME_EVENT', 'themes': ['機器人', 'AI視覺', '題材型']},
 '2360': {'hybrid_taxons': [{'reason': 'AI/HPC 測試設備受先進封裝擴產帶動，但本業仍為多元測試設備。', 'taxon': 'SEMICAP_ADV_PACKAGING_CORE', 'weight': 0.08}],
          'name': '致茂',
          'primary_taxon': 'TEST_AUTOMATION_EQUIPMENT',
          'themes': ['測試設備', '自動化測試', '電源測試', 'AI伺服器測試']},
 '2363': {'name': '矽統', 'primary_taxon': 'LEGACY_CONSUMER_IC_TURNAROUND', 'themes': ['晶片組', '消費性IC', '轉機題材']},
 '2367': {'name': '燿華', 'primary_taxon': 'PCB_STANDARD_BOARD', 'themes': ['PCB', '車用']},
 '2368': {'name': '金像電', 'primary_taxon': 'AI_SERVER_PCB_HIGH_VISIBILITY', 'themes': ['AI伺服器主板', 'PCB', '高階PCB']},
 '2369': {'name': '菱生', 'primary_taxon': 'GENERAL_OSAT_TEST_LEADFRAME', 'themes': ['封測', '導線架封裝', '車用']},
 '2371': {'name': '大同', 'primary_taxon': 'GRID_ASSET_TURNAROUND', 'themes': ['重電', '電網', '資產', '轉機題材']},
 '2376': {'name': '技嘉', 'primary_taxon': 'AI_SERVER_BOARD_SYSTEM', 'themes': ['主板', 'GPU', 'AI伺服器系統']},
 '2377': {'name': '微星', 'primary_taxon': 'AI_SERVER_BOARD_SYSTEM', 'themes': ['主板', 'GPU', 'AI伺服器系統']},
 '2379': {'name': '瑞昱', 'primary_taxon': 'PLATFORM_IC_LEADER', 'themes': ['網通晶片', '音訊晶片', '平台型IC', 'AI Edge']},
 '2382': {'hybrid_taxons': [{'reason': 'AI 伺服器為主要成長動能，但仍保留 NB/ODM 本業權重。', 'taxon': 'AI_SERVER_ODM', 'weight': 0.45}],
          'name': '廣達',
          'primary_taxon': 'PC_NB_ODM',
          'themes': ['NB ODM', 'AI伺服器', '資料中心']},
 '2383': {'name': '台光電', 'primary_taxon': 'AI_CCL_HIGH_VISIBILITY', 'themes': ['CCL', '高速材料', 'AI伺服器', '高階PCB材料']},
 '2388': {'name': '威盛', 'primary_taxon': 'IC_DESIGN_ASIC', 'themes': ['AI邊緣運算', '車用']},
 '2392': {'name': '正崴', 'primary_taxon': 'CONNECTOR_STANDARD', 'themes': ['連接器', '電源', '一般連接器']},
 '2395': {'name': '研華', 'primary_taxon': 'IPC_EDGE_AI', 'themes': ['工業電腦', 'IPC', 'Edge AI', '邊緣運算']},
 '2401': {'name': '凌陽', 'primary_taxon': 'CONSUMER_MCU_CONTROL_IC', 'themes': ['多媒體IC', '消費性IC', 'MCU/控制IC']},
 '2404': {'hybrid_taxons': [{'reason': 'AI/HPC 擴產帶動廠務需求，但仍是工程/廠務模型。', 'taxon': 'SEMICAP_ADV_PACKAGING_CORE', 'weight': 0.08}],
          'name': '漢唐',
          'primary_taxon': 'FAB_FACILITY_MATERIALS',
          'themes': ['廠務', '無塵室', '半導體工程', 'AI晶圓廠建置']},
 '2408': {'name': '南亞科', 'primary_taxon': 'MEMORY_MANUFACTURING_CYCLE', 'themes': ['DRAM', '記憶體製造', 'P/B週期']},
 '2409': {'name': '友達', 'primary_taxon': 'DISPLAY_LED_CYCLE', 'themes': ['面板', '顯示技術', '光電循環']},
 '2412': {'name': '中華電', 'primary_taxon': 'TELECOM_DEFENSIVE', 'themes': ['電信', '基礎網路', '高殖利率', '防禦型']},
 '2421': {'name': '建準', 'primary_taxon': 'THERMAL_AIR', 'themes': ['散熱風扇', '傳統散熱']},
 '2434': {'name': '統懋', 'primary_taxon': 'POWER_DISCRETE_COMPONENT_CYCLE', 'themes': ['功率電晶體', '二極體', '功率半導體']},
 '2436': {'name': '偉詮電', 'primary_taxon': 'CONSUMER_MCU_CONTROL_IC', 'themes': ['MCU', '電源管理IC', '消費性控制IC']},
 '2441': {'name': '超豐', 'primary_taxon': 'GENERAL_OSAT_TEST_LEADFRAME', 'themes': ['封測', 'IC封裝', '成熟封測']},
 '2449': {'hybrid_taxons': [{'reason': 'AI/HPC 測試需求增加，但仍為封測測試服務，權重保守。', 'taxon': 'PROBE_AI_ASIC', 'weight': 0.08}],
          'name': '京元電子',
          'primary_taxon': 'OSAT_AI_HPC_TESTING',
          'themes': ['測試', 'AI晶片測試', 'HPC測試']},
 '2451': {'name': '創見', 'primary_taxon': 'MEMORY_MODULE_STORAGE_BRAND', 'themes': ['記憶體模組', '儲存品牌']},
 '2453': {'name': '凌群', 'primary_taxon': 'IT_SERVICES_SYSTEM_INTEGRATION', 'themes': ['系統整合', '資訊服務']},
 '2454': {'hybrid_taxons': [{'reason': 'AI ASIC 已反映於成長預期，但仍非純 AI ASIC，權重降至 20%。',
                             'taxon': 'IC_DESIGN_ASIC_HIGH_VISIBILITY',
                             'weight': 0.2}],
          'name': '聯發科',
          'primary_taxon': 'PLATFORM_IC_LEADER',
          'themes': ['手機晶片', '平台型IC', 'AI Edge', 'AI ASIC']},
 '2458': {'name': '義隆', 'primary_taxon': 'CONSUMER_INTERFACE_SENSOR_IC', 'themes': ['觸控IC', 'MCU', '人機介面IC']},
 '2464': {'name': '盟立', 'primary_taxon': 'INDUSTRIAL_AUTOMATION_CORE', 'themes': ['自動化', '設備整合', '工業自動化']},
 '2467': {'name': '志聖', 'primary_taxon': 'SEMICAP_ADV_PACKAGING_CORE', 'themes': ['設備', 'PCB設備', '先進封裝題材']},
 '2480': {'name': '敦陽科', 'primary_taxon': 'IT_SERVICES_SYSTEM_INTEGRATION', 'themes': ['系統整合', '資訊服務', '高殖利率']},
 '2481': {'name': '強茂', 'primary_taxon': 'POWER_DISCRETE_COMPONENT_CYCLE', 'themes': ['功率半導體', '二極體', '車用']},
 '2486': {'name': '一詮', 'primary_taxon': 'THERMAL_AIR', 'themes': ['散熱零件', 'EPS失真防護']},
 '2492': {'name': '華新科', 'primary_taxon': 'PASSIVE_COMPONENT_CYCLE', 'themes': ['被動元件', 'MLCC', '景氣循環']},
 '2603': {'name': '長榮', 'primary_taxon': 'SHIPPING_CYCLE', 'themes': ['海運']},
 '2609': {'name': '陽明', 'primary_taxon': 'SHIPPING_CYCLE', 'themes': ['海運']},
 '2615': {'name': '萬海', 'primary_taxon': 'SHIPPING_CYCLE', 'themes': ['海運']},
 '2881': {'name': '富邦金', 'primary_taxon': 'FINANCIAL_LIFE_INSURANCE_HOLDCO', 'themes': ['金控', '壽險', '保險', '金融']},
 '2882': {'name': '國泰金', 'primary_taxon': 'FINANCIAL_LIFE_INSURANCE_HOLDCO', 'themes': ['金控', '壽險', '銀行', '金融']},
 '2884': {'name': '玉山金', 'primary_taxon': 'FINANCIAL_BANK_HOLDCO_QUALITY', 'themes': ['金控', '銀行', '金融', '防禦型']},
 '2886': {'name': '兆豐金', 'primary_taxon': 'FINANCIAL_BANK_HOLDCO_QUALITY', 'themes': ['金控', '官股金控', '銀行', '金融']},
 '2891': {'name': '中信金', 'primary_taxon': 'FINANCIAL_BANK_HOLDCO_QUALITY', 'themes': ['金控', '銀行', '金融']},
 '2892': {'name': '第一金', 'primary_taxon': 'FINANCIAL_BANK_HOLDCO_QUALITY', 'themes': ['金控', '官股金控', '銀行', '金融']},
 '3006': {'name': '晶豪科', 'primary_taxon': 'MEMORY_MANUFACTURING_CYCLE', 'themes': ['記憶體IC', 'DRAM', 'P/B週期']},
 '3008': {'name': '大立光', 'primary_taxon': 'OPTICS_LENS_LEADER', 'themes': ['手機鏡頭', '高階鏡頭', 'AI光學', '車用鏡頭']},
 '3013': {'name': '晟銘電', 'primary_taxon': 'AI_SERVER_CHASSIS_CORE', 'themes': ['機殼', 'AI伺服器', '伺服器機構件']},
 '3014': {'name': '聯陽', 'primary_taxon': 'HIGH_SPEED_INTERFACE_IC', 'themes': ['高速介面', 'I/O控制IC', '平台型IC']},
 '3015': {'name': '全漢', 'primary_taxon': 'POWER_SUPPLY_STANDARD', 'themes': ['電源', '一般電源']},
 '3016': {'name': '嘉晶', 'primary_taxon': 'SILICON_WAFER_CYCLE', 'themes': ['磊晶矽晶圓', '矽晶圓', '半導體上游材料']},
 '3017': {'name': '奇鋐', 'primary_taxon': 'THERMAL_LIQUID_CORE', 'themes': ['AI散熱', '水冷', '液冷', 'AI伺服器']},
 '3019': {'name': '亞光', 'primary_taxon': 'OPTICS_MODULE_CYCLE', 'themes': ['光學模組', '車用光學', '光學循環']},
 '3025': {'name': '星通', 'primary_taxon': 'NETWORK_EQUIPMENT_STANDARD', 'themes': ['網通', '一般網通']},
 '3026': {'name': '禾伸堂', 'primary_taxon': 'PASSIVE_COMPONENT_CYCLE', 'themes': ['被動元件', 'MLCC', '景氣循環']},
 '3029': {'name': '零壹', 'primary_taxon': 'CLOUD_SECURITY_SERVICES', 'themes': ['資安', '雲端', '代理通路', '高殖利率']},
 '3034': {'name': '聯詠', 'primary_taxon': 'DISPLAY_DRIVER_IC_CYCLE', 'themes': ['驅動IC', 'TDDI', '顯示IC', '成熟獲利']},
 '3035': {'name': '智原', 'primary_taxon': 'IC_DESIGN_ASIC_SERVICE', 'themes': ['ASIC', '設計服務', 'NRE']},
 '3037': {'name': '欣興', 'primary_taxon': 'ABF_SUBSTRATE', 'themes': ['AI載板', 'HPC', 'ABF', '循環復甦']},
 '3041': {'name': '揚智', 'primary_taxon': 'LEGACY_CONSUMER_IC_TURNAROUND', 'themes': ['多媒體IC', '機上盒晶片', '轉機題材']},
 '3044': {'name': '健鼎', 'primary_taxon': 'PCB_STANDARD_BOARD', 'themes': ['PCB', '伺服器', '一般PCB']},
 '3045': {'name': '台灣大', 'primary_taxon': 'TELECOM_DEFENSIVE', 'themes': ['電信', '基礎網路', '高殖利率', '防禦型']},
 '3078': {'name': '僑威', 'primary_taxon': 'POWER_SUPPLY_STANDARD', 'themes': ['電源', '一般電源']},
 '3081': {'name': '聯亞', 'primary_taxon': 'OPTICAL_COMM_CPO_HIGH_VISIBILITY', 'themes': ['光通訊', 'CPO', '矽光子', '高能見度']},
 '3094': {'name': '聯傑', 'primary_taxon': 'LEGACY_CONSUMER_IC_TURNAROUND', 'themes': ['網通IC', '通訊IC', '轉機題材']},
 '3131': {'name': '弘塑', 'primary_taxon': 'SEMICAP_ADV_PACKAGING_CORE', 'themes': ['CoWoS', '濕製程', '先進封裝設備']},
 '3135': {'name': '凌航', 'primary_taxon': 'MEMORY_MODULE_STORAGE_BRAND', 'themes': ['記憶體產品', '記憶體模組', '儲存']},
 '3163': {'name': '波若威', 'primary_taxon': 'OPTICAL_COMM_CPO_HIGH_VISIBILITY', 'themes': ['光通訊', 'AI data center', '800G/CPO題材', '高能見度']},
 '3189': {'name': '景碩', 'primary_taxon': 'ABF_SUBSTRATE', 'themes': ['ABF', '載板', 'AI/HPC']},
 '3227': {'name': '原相', 'primary_taxon': 'CONSUMER_INTERFACE_SENSOR_IC', 'themes': ['感測IC', '滑鼠晶片', '人機介面IC']},
 '3231': {'hybrid_taxons': [{'reason': 'AI 伺服器成長曲線明確，但仍屬 ODM/EMS 複合型。', 'taxon': 'AI_SERVER_ODM', 'weight': 0.4}],
          'name': '緯創',
          'primary_taxon': 'PC_NB_ODM',
          'themes': ['NB ODM', 'AI伺服器', '資料中心']},
 '3257': {'name': '虹冠電', 'primary_taxon': 'POWER_MANAGEMENT_IC_DESIGN', 'themes': ['電源管理IC', '功率IC', '類比IC']},
 '3260': {'name': '威剛', 'primary_taxon': 'MEMORY_MODULE_STORAGE_BRAND', 'themes': ['記憶體模組', '儲存品牌']},
 '3264': {'name': '欣銓', 'primary_taxon': 'OSAT_AI_HPC_TESTING', 'themes': ['測試', '車用', 'HPC測試']},
 '3324': {'name': '雙鴻', 'primary_taxon': 'THERMAL_AI_COMPONENTS', 'themes': ['AI散熱', '水冷', '液冷', 'AI伺服器']},
 '3338': {'name': '泰碩', 'primary_taxon': 'THERMAL_AI_COMPONENTS', 'themes': ['散熱', 'AI散熱零組件']},
 '3362': {'name': '先進光', 'primary_taxon': 'OPTICS_MODULE_CYCLE', 'themes': ['光學鏡頭', '光學循環']},
 '3363': {'name': '上詮', 'primary_taxon': 'OPTICAL_COMM_CPO_HIGH_VISIBILITY', 'themes': ['光通訊', 'CPO題材', '矽光子']},
 '3374': {'name': '精材', 'primary_taxon': 'CIS_SEMICONDUCTOR_OPTICS', 'themes': ['CIS封裝', '晶圓級封裝', '台積電轉投資', '封測']},
 '3380': {'hybrid_taxons': [{'reason': '低軌衛星為附加題材，不直接套 AI data center switch 倍率。', 'taxon': 'SPACE_LEO_SATELLITE', 'weight': 0.05}],
          'name': '明泰',
          'primary_taxon': 'NETWORK_EQUIPMENT_STANDARD',
          'themes': ['網通', '低軌衛星', '通訊設備']},
 '3406': {'name': '玉晶光', 'primary_taxon': 'OPTICS_LENS_LEADER', 'themes': ['手機鏡頭', '高階鏡頭', '光學']},
 '3413': {'name': '京鼎', 'primary_taxon': 'SEMICAP_GENERAL_EQUIPMENT', 'themes': ['半導體設備', '設備零組件', '先進製程']},
 '3443': {'name': '創意', 'primary_taxon': 'IC_DESIGN_ASIC_SERVICE', 'themes': ['ASIC', '設計服務', 'NRE', 'HPC']},
 '3450': {'name': '聯鈞', 'primary_taxon': 'OPTICAL_COMM_CPO_HIGH_VISIBILITY', 'themes': ['光通訊', 'CPO題材', 'AI data center']},
 '3455': {'hybrid_taxons': [{'reason': '高階 PCB/半導體檢測受先進封裝題材帶動，但 EPS/訂單仍需驗證。', 'taxon': 'SEMICAP_ADV_PACKAGING_CORE', 'weight': 0.08}],
          'name': '由田',
          'primary_taxon': 'TEST_AUTOMATION_EQUIPMENT',
          'themes': ['AOI', '檢測設備', 'PCB/半導體檢測', 'AI伺服器檢測']},
 '3481': {'name': '群創', 'primary_taxon': 'DISPLAY_LED_CYCLE', 'themes': ['面板', '顯示技術', 'FOPLP', '面板級扇出型封裝']},
 '3483': {'name': '力致', 'primary_taxon': 'THERMAL_AI_COMPONENTS', 'themes': ['散熱', 'AI散熱零組件']},
 '3491': {'name': '昇達科', 'primary_taxon': 'SPACE_LEO_SATELLITE', 'themes': ['毫米波', '低軌衛星']},
 '3529': {'name': '力旺', 'primary_taxon': 'IC_DESIGN_IP_ROYALTY', 'themes': ['矽智財', 'IP授權', 'Royalty']},
 '3530': {'name': '晶相光', 'primary_taxon': 'CIS_SEMICONDUCTOR_OPTICS', 'themes': ['CIS', '影像感測', 'IC設計']},
 '3532': {'name': '台勝科', 'primary_taxon': 'SILICON_WAFER_CYCLE', 'themes': ['矽晶圓', '半導體材料', '上游材料']},
 '3533': {'name': '嘉澤', 'primary_taxon': 'HIGH_SPEED_CONNECTOR_CORE', 'themes': ['高速連接器', 'AI伺服器', '伺服器連接器']},
 '3545': {'name': '敦泰', 'primary_taxon': 'DISPLAY_DRIVER_IC_CYCLE', 'themes': ['驅動IC', '觸控IC', '顯示IC', '循環']},
 '3552': {'name': '同致', 'primary_taxon': 'EV_AUTO_ELECTRONICS', 'themes': ['ADAS', '車用電子']},
 '3583': {'name': '辛耘', 'primary_taxon': 'SEMICAP_ADV_PACKAGING_CORE', 'themes': ['CoWoS', '半導體設備', '先進封裝']},
 '3588': {'name': '通嘉', 'primary_taxon': 'POWER_MANAGEMENT_IC_DESIGN', 'themes': ['電源管理IC', '類比IC', '功率IC', 'PE失真防護']},
 '3592': {'name': '瑞鼎', 'primary_taxon': 'DISPLAY_DRIVER_IC_CYCLE', 'themes': ['驅動IC', '顯示IC', 'TDDI']},
 '3596': {'name': '智易', 'primary_taxon': 'NETWORK_EQUIPMENT_STANDARD', 'themes': ['網通', '一般網通']},
 '3605': {'name': '宏致', 'primary_taxon': 'CONNECTOR_STANDARD', 'themes': ['連接器', '一般連接器']},
 '3630': {'name': '新鉅科', 'primary_taxon': 'OPTICS_MODULE_CYCLE', 'themes': ['光學鏡頭', '光學循環']},
 '3653': {'name': '健策', 'primary_taxon': 'THERMAL_LIQUID_CORE', 'themes': ['均熱片', '散熱', 'AI伺服器', '液冷/水冷']},
 '3661': {'name': '世芯-KY', 'primary_taxon': 'IC_DESIGN_ASIC_HIGH_VISIBILITY', 'themes': ['AI ASIC', 'HPC', '客製化晶片', '高能見度ASIC']},
 '3665': {'hybrid_taxons': [{'reason': '車用/EV 仍是中長期成長線，維持低權重。', 'taxon': 'EV_AUTO_ELECTRONICS', 'weight': 0.1}],
          'name': '貿聯-KY',
          'primary_taxon': 'HIGH_SPEED_CONNECTOR_CORE',
          'themes': ['高速傳輸', '車用電子', 'AI伺服器', '線束']},
 '3680': {'name': '家登', 'primary_taxon': 'SEMIMAT_ADVANCED_CONSUMABLES', 'themes': ['EUV', '晶圓載具', '半導體耗材']},
 '3686': {'name': '達能', 'primary_taxon': 'SILICON_WAFER_CYCLE', 'themes': ['矽晶圓', '半導體上游材料', '循環股']},
 '3693': {'name': '營邦', 'primary_taxon': 'AI_SERVER_CHASSIS_CORE', 'themes': ['伺服器機殼', 'AI伺服器機構件']},
 '3704': {'name': '合勤控', 'primary_taxon': 'NETWORK_EQUIPMENT_STANDARD', 'themes': ['網通', '通訊', '一般網通']},
 '3706': {'name': '神達', 'primary_taxon': 'AI_SERVER_ODM', 'themes': ['AI伺服器']},
 '3708': {'name': '上緯投控', 'primary_taxon': 'WIND_POWER_INFRA', 'themes': ['風電材料', '綠能', '風電', '循環防護']},
 '3711': {'name': '日月光投控', 'primary_taxon': 'OSAT_AI_HPC_TESTING', 'themes': ['先進封裝', '封測', 'AI晶片']},
 '3714': {'name': '富采', 'primary_taxon': 'DISPLAY_LED_CYCLE', 'themes': ['LED', 'Micro LED', '光電']},
 '3715': {'name': '定穎投控', 'primary_taxon': 'AI_SERVER_PCB_HIGH_VISIBILITY', 'themes': ['PCB', '車用', 'AI伺服器PCB', 'PE失真防護']},
 '4105': {'name': '東洋', 'primary_taxon': 'PHARMA_CDMO_PROFIT', 'themes': ['藥廠', '獲利型生技']},
 '4128': {'name': '中裕', 'primary_taxon': 'BIOTECH_NEW_DRUG_EVENT', 'themes': ['新藥', '里程碑', '事件型']},
 '4510': {'name': '高鋒', 'primary_taxon': 'MACHINE_TOOL_CYCLE', 'themes': ['工具機']},
 '4526': {'name': '東台', 'primary_taxon': 'MACHINE_TOOL_CYCLE', 'themes': ['工具機', '自動化']},
 '4543': {'name': '萬在', 'primary_taxon': 'THERMAL_AI_COMPONENTS', 'themes': ['散熱', 'AI散熱零組件']},
 '4743': {'name': '合一', 'primary_taxon': 'BIOTECH_NEW_DRUG_EVENT', 'themes': ['新藥', '里程碑', '事件型']},
 '4904': {'name': '遠傳', 'primary_taxon': 'TELECOM_DEFENSIVE', 'themes': ['電信', '基礎網路', '高殖利率', '防禦型']},
 '4906': {'name': '正文', 'primary_taxon': 'NETWORK_EQUIPMENT_STANDARD', 'themes': ['網通', '一般網通']},
 '4908': {'name': '前鼎', 'primary_taxon': 'OPTICAL_COMM_STANDARD', 'themes': ['光通訊', '一般光通訊']},
 '4919': {'name': '新唐', 'primary_taxon': 'CONSUMER_MCU_CONTROL_IC', 'themes': ['MCU', '消費性IC', '工控IC']},
 '4938': {'hybrid_taxons': [{'reason': 'AI server/AI PC 屬新成長曲線，但純度低於廣達、緯創。', 'taxon': 'AI_SERVER_ODM', 'weight': 0.08}],
          'name': '和碩',
          'primary_taxon': 'PC_NB_ODM',
          'themes': ['ODM', 'EMS', 'PC/NB代工', 'AI Server/AI PC 題材']},
 '4952': {'name': '凌通', 'primary_taxon': 'CONSUMER_MCU_CONTROL_IC', 'themes': ['MCU', '語音IC', '消費性IC']},
 '4953': {'name': '緯軟', 'primary_taxon': 'IT_SERVICES_SYSTEM_INTEGRATION', 'themes': ['軟體服務', '資訊委外']},
 '4961': {'name': '天鈺', 'primary_taxon': 'DISPLAY_DRIVER_IC_CYCLE', 'themes': ['驅動IC', '電源管理IC', '顯示IC']},
 '4966': {'name': '譜瑞-KY', 'primary_taxon': 'HIGH_SPEED_INTERFACE_IC', 'themes': ['高速介面', 'USB', '車用', 'AI PC']},
 '4967': {'name': '十銓', 'primary_taxon': 'MEMORY_MODULE_STORAGE_BRAND', 'themes': ['記憶體模組', '儲存品牌']},
 '4968': {'name': '立積', 'primary_taxon': 'RF_CONNECTIVITY_IC', 'themes': ['RF IC', 'WiFi FEM', '無線通訊IC']},
 '4976': {'name': '佳凌', 'primary_taxon': 'OPTICS_MODULE_CYCLE', 'themes': ['光學鏡頭', '光學循環']},
 '4977': {'name': '眾達-KY', 'primary_taxon': 'OPTICAL_COMM_STANDARD', 'themes': ['光通訊', '一般光通訊']},
 '4979': {'name': '華星光', 'primary_taxon': 'OPTICAL_COMM_CPO_HIGH_VISIBILITY', 'themes': ['光通訊', 'AI data center', '800G/CPO題材']},
 '5212': {'name': '凌網', 'primary_taxon': 'IT_SERVICES_SYSTEM_INTEGRATION', 'themes': ['資訊服務', '系統整合']},
 '5222': {'name': '全訊', 'primary_taxon': 'COMPOUND_SEMICONDUCTOR_OPTO', 'themes': ['GaAs', 'RF功率放大器', '化合物半導體']},
 '5269': {'name': '祥碩', 'primary_taxon': 'IC_DESIGN_ASIC', 'themes': ['高速傳輸', 'IC設計']},
 '5274': {'hybrid_taxons': [{'reason': 'BMC 受 AI server 平台升級帶動，但主分類已含資料中心高能見度，權重保守。',
                             'taxon': 'IC_DESIGN_ASIC_HIGH_VISIBILITY',
                             'weight': 0.08}],
          'name': '信驊',
          'primary_taxon': 'IC_DESIGN_SERVER_BMC_HIGH_VISIBILITY',
          'themes': ['伺服器BMC', '資料中心', 'AI伺服器', '高能見度']},
 '5285': {'name': '界霖', 'primary_taxon': 'SEMIMAT_POWER_LEADFRAME', 'themes': ['導線架', '功率元件材料', '車用半導體材料']},
 '5347': {'name': '世界', 'primary_taxon': 'FOUNDRY_MATURE', 'themes': ['成熟製程', '電源管理IC代工', '晶圓代工']},
 '5388': {'name': '中磊', 'primary_taxon': 'NETWORK_EQUIPMENT_STANDARD', 'themes': ['網通', '一般網通']},
 '5426': {'name': '振發', 'primary_taxon': 'SERVER_CHASSIS_STANDARD', 'themes': ['機殼', '工業電腦機構件']},
 '5443': {'hybrid_taxons': [{'reason': '先進封裝/半導體設備題材提升估值，但仍偏一般設備與檢測，改用一般設備權重。', 'taxon': 'SEMICAP_GENERAL_EQUIPMENT', 'weight': 0.08}],
          'name': '均豪',
          'primary_taxon': 'TEST_AUTOMATION_EQUIPMENT',
          'themes': ['AOI', '設備', '自動化檢測', '半導體設備']},
 '5471': {'name': '松翰', 'primary_taxon': 'CONSUMER_MCU_CONTROL_IC', 'themes': ['MCU', '影像控制IC', '消費性控制IC']},
 '5483': {'name': '中美晶', 'primary_taxon': 'SILICON_WAFER_CYCLE', 'themes': ['矽晶圓', '半導體材料', '上游材料']},
 '6112': {'name': '邁達特', 'primary_taxon': 'IT_SERVICES_SYSTEM_INTEGRATION', 'themes': ['系統整合', '資訊服務']},
 '6117': {'hybrid_taxons': [{'reason': '一般機殼中具部分 AI server 機構件轉型，但純度低於核心機構件。', 'taxon': 'AI_SERVER_CHASSIS_CORE', 'weight': 0.12}],
          'name': '迎廣',
          'primary_taxon': 'SERVER_CHASSIS_STANDARD',
          'themes': ['機殼', '伺服器機構件']},
 '6125': {'name': '廣運', 'primary_taxon': 'ROBOTICS_THEME_EVENT', 'themes': ['自動化', '物流設備', '機器人題材', 'AI應用']},
 '6139': {'name': '亞翔', 'primary_taxon': 'FAB_FACILITY_MATERIALS', 'themes': ['廠務', '無塵室']},
 '6182': {'name': '合晶', 'primary_taxon': 'SILICON_WAFER_CYCLE', 'themes': ['矽晶圓', '半導體材料', '上游材料']},
 '6187': {'name': '萬潤', 'primary_taxon': 'SEMICAP_ADV_PACKAGING_CORE', 'themes': ['CoWoS', '設備', '先進封裝']},
 '6188': {'name': '廣明', 'primary_taxon': 'ROBOTICS_THEME_EVENT', 'themes': ['機器人題材', '自動化', '低毛利硬體']},
 '6196': {'hybrid_taxons': [{'reason': 'AI/HPC 擴產帶動廠務與設備整合，但仍非純半導體設備。', 'taxon': 'SEMICAP_ADV_PACKAGING_CORE', 'weight': 0.08}],
          'name': '帆宣',
          'primary_taxon': 'FAB_FACILITY_MATERIALS',
          'themes': ['廠務', '半導體工程', '設備整合', 'AI晶圓廠建置']},
 '6197': {'name': '佳必琪', 'primary_taxon': 'HIGH_SPEED_CONNECTOR_CORE', 'themes': ['高速連接', '線材', 'AI伺服器']},
 '6202': {'name': '盛群', 'primary_taxon': 'CONSUMER_MCU_CONTROL_IC', 'themes': ['MCU', '消費性控制IC']},
 '6209': {'name': '今國光', 'primary_taxon': 'OPTICS_MODULE_CYCLE', 'themes': ['光學鏡頭', '光學循環']},
 '6213': {'name': '聯茂', 'primary_taxon': 'CCL_STANDARD_CYCLE', 'themes': ['CCL', '銅箔基板', 'PCB材料', '高階材料']},
 '6214': {'name': '精誠', 'primary_taxon': 'IT_SERVICES_SYSTEM_INTEGRATION', 'themes': ['系統整合', '資安', '資訊服務']},
 '6217': {'name': '中探針', 'primary_taxon': 'TURNAROUND_PROBE_TEST_THEME', 'themes': ['測試針', '探針', '車用測試', '轉機題材']},
 '6223': {'name': '旺矽', 'primary_taxon': 'PROBE_AI_ASIC', 'themes': ['AI ASIC', 'CPO', 'MEMS', '探針卡', '高階測試介面']},
 '6230': {'name': '尼得科超眾', 'primary_taxon': 'THERMAL_AIR', 'themes': ['散熱', '傳統散熱']},
 '6239': {'name': '力成', 'primary_taxon': 'MEMORY_OSAT_CYCLE', 'themes': ['記憶體封測', '封測', '先進封裝題材']},
 '6243': {'name': '迅杰', 'primary_taxon': 'CONSUMER_MCU_CONTROL_IC', 'themes': ['鍵盤控制IC', '消費性控制IC']},
 '6257': {'name': '矽格', 'primary_taxon': 'GENERAL_OSAT_TEST_LEADFRAME', 'themes': ['封測', '測試', '成熟封測']},
 '6271': {'name': '同欣電', 'primary_taxon': 'RF_MODULE_PACKAGING', 'themes': ['RF封裝', '車用', '特殊封裝']},
 '6274': {'name': '台燿', 'primary_taxon': 'AI_CCL_HIGH_VISIBILITY', 'themes': ['CCL', '高速材料', 'AI伺服器', '高階PCB材料']},
 '6275': {'name': '元山', 'primary_taxon': 'THERMAL_AIR', 'themes': ['風扇', '散熱', '傳統散熱']},
 '6282': {'name': '康舒', 'primary_taxon': 'POWER_SUPPLY_STANDARD', 'themes': ['電源', '一般電源', 'PE失真防護']},
 '6285': {'hybrid_taxons': [{'reason': '低軌衛星為附加題材，權重降至 5%。', 'taxon': 'SPACE_LEO_SATELLITE', 'weight': 0.05}],
          'name': '啟碁',
          'primary_taxon': 'NETWORK_EQUIPMENT_STANDARD',
          'themes': ['低軌衛星', '網通', '通訊設備', 'AI邊緣網通']},
 '6290': {'name': '良維', 'primary_taxon': 'HIGH_SPEED_CONNECTOR_CORE', 'themes': ['線材', '電源線', '高速線材']},
 '6409': {'name': '旭隼', 'primary_taxon': 'UPS_POWER_QUALITY', 'themes': ['UPS', '不斷電系統', '資料中心能源管理', '電源']},
 '6412': {'name': '群電', 'primary_taxon': 'POWER_SUPPLY_STANDARD', 'themes': ['電源', '一般電源']},
 '6414': {'name': '樺漢', 'primary_taxon': 'IPC_EDGE_AI', 'themes': ['工業電腦', 'IPC', 'Edge AI', '鴻海集團']},
 '6415': {'name': '矽力*-KY', 'primary_taxon': 'POWER_MANAGEMENT_IC_DESIGN', 'themes': ['電源管理IC', '類比IC', '高毛利IC設計']},
 '6438': {'name': '迅得', 'primary_taxon': 'SEMICAP_GENERAL_EQUIPMENT', 'themes': ['自動化', '半導體設備']},
 '6442': {'name': '光聖', 'primary_taxon': 'OPTICAL_COMM_CPO_HIGH_VISIBILITY', 'themes': ['光通訊', '矽光子', 'CPO', 'AI data center']},
 '6451': {'name': '訊芯-KY', 'primary_taxon': 'OPTICAL_COMM_CPO_HIGH_VISIBILITY', 'themes': ['矽光子', '封裝', 'CPO題材']},
 '6462': {'name': '神盾', 'primary_taxon': 'IC_DESIGN_ASIC', 'themes': ['邊緣AI', '感測']},
 '6472': {'name': '保瑞', 'primary_taxon': 'PHARMA_CDMO_PROFIT', 'themes': ['藥廠', 'CDMO', '獲利型生技']},
 '6488': {'name': '環球晶', 'primary_taxon': 'SILICON_WAFER_CYCLE', 'themes': ['矽晶圓', '半導體材料', '上游材料']},
 '6510': {'name': '精測', 'primary_taxon': 'PROBE_AI_ASIC', 'themes': ['AI ASIC', 'HPC', '探針卡', '高階測試介面']},
 '6515': {'name': '穎崴', 'primary_taxon': 'PROBE_AI_ASIC', 'themes': ['AI ASIC', '測試介面', '高階探針卡']},
 '6525': {'name': '捷敏-KY', 'primary_taxon': 'GENERAL_OSAT_TEST_LEADFRAME', 'themes': ['封測', '功率半導體封裝', '車用']},
 '6526': {'name': '達發', 'primary_taxon': 'RF_CONNECTIVITY_IC', 'themes': ['網通IC', '藍牙音訊IC', 'Connectivity IC']},
 '6530': {'name': '創威', 'primary_taxon': 'OPTICAL_COMM_STANDARD', 'themes': ['光通訊', '一般光通訊']},
 '6531': {'hybrid_taxons': [{'reason': '記憶體景氣循環仍影響估值，改用第五批拆分後的記憶體製造週期並降低權重。', 'taxon': 'MEMORY_MANUFACTURING_CYCLE', 'weight': 0.15}],
          'name': '愛普*',
          'primary_taxon': 'MEMORY_IP_AI',
          'themes': ['記憶體IP', 'AI記憶體', 'IP/Royalty', '記憶體循環']},
 '6533': {'name': '晶心科', 'primary_taxon': 'IC_DESIGN_IP_ROYALTY', 'themes': ['RISC-V', 'IP', 'Royalty']},
 '6552': {'name': '易華電', 'primary_taxon': 'DISPLAY_COF_MATERIALS', 'themes': ['COF', '驅動IC材料', '顯示材料']},
 '6573': {'name': '虹揚-KY', 'primary_taxon': 'POWER_DISCRETE_COMPONENT_CYCLE', 'themes': ['整流器', '功率半導體', '車用']},
 '6584': {'name': '南俊國際', 'primary_taxon': 'SERVER_RAIL_HIGH_VISIBILITY', 'themes': ['滑軌', '高毛利機構件']},
 '6589': {'name': '台康生技', 'primary_taxon': 'BIOTECH_CELL_THERAPY_BIOSIMILAR', 'themes': ['生物相似藥', '里程碑', '事件型']},
 '6591': {'name': '動力-KY', 'primary_taxon': 'THERMAL_AIR', 'themes': ['風扇', '散熱', '傳統散熱']},
 '6640': {'name': '均華', 'primary_taxon': 'SEMICAP_ADV_PACKAGING_CORE', 'themes': ['先進封裝設備', 'CoWoS']},
 '6643': {'name': 'M31', 'primary_taxon': 'IC_DESIGN_IP_ROYALTY', 'themes': ['矽智財', 'IP授權', 'Royalty']},
 '6664': {'name': '群翊', 'primary_taxon': 'SEMICAP_GENERAL_EQUIPMENT', 'themes': ['設備', 'PCB設備']},
 '6669': {'name': '緯穎', 'primary_taxon': 'AI_SERVER_ODM', 'themes': ['AI伺服器', '資料中心', '雲端服務供應商']},
 '6683': {'name': '雍智科技', 'primary_taxon': 'PROBE_TEST_INTERFACE', 'themes': ['測試介面']},
 '6689': {'name': '伊雲谷', 'primary_taxon': 'CLOUD_SECURITY_SERVICES', 'themes': ['雲端', '雲端服務', 'AWS代理']},
 '6695': {'name': '芯鼎', 'primary_taxon': 'EDGE_AI_SENSOR_SOC', 'themes': ['AI影像IC', '影像處理', 'Edge AI']},
 '6712': {'name': '長聖', 'primary_taxon': 'BIOTECH_CELL_THERAPY_BIOSIMILAR', 'themes': ['細胞治療', '再生醫療', '事件型']},
 '6715': {'name': '嘉基', 'primary_taxon': 'HIGH_SPEED_CONNECTOR_CORE', 'themes': ['高速連接器', 'PE失真防護']},
 '6719': {'name': '力智', 'primary_taxon': 'POWER_MANAGEMENT_IC_DESIGN', 'themes': ['電源管理IC', '功率IC', '類比IC']},
 '6751': {'name': '智聯服務', 'primary_taxon': 'IT_SERVICES_SYSTEM_INTEGRATION', 'themes': ['資訊服務', '系統整合']},
 '6756': {'name': '威鋒電子', 'primary_taxon': 'HIGH_SPEED_INTERFACE_IC', 'themes': ['USB控制IC', '高速介面', '平台型IC']},
 '6770': {'name': '力積電', 'primary_taxon': 'FOUNDRY_MATURE', 'themes': ['成熟製程', '記憶體代工', '晶圓代工']},
 '6789': {'name': '采鈺', 'primary_taxon': 'CIS_SEMICONDUCTOR_OPTICS', 'themes': ['CIS', '影像感測', '半導體光學', '先進封裝']},
 '6799': {'name': '來頡', 'primary_taxon': 'POWER_MANAGEMENT_IC_DESIGN', 'themes': ['電源管理IC', '類比IC', '功率IC']},
 '6805': {'hybrid_taxons': [{'reason': '水冷/散熱題材已影響估值，但主業仍為高階機構件，權重下修。', 'taxon': 'THERMAL_LIQUID_CORE', 'weight': 0.1}],
          'name': '富世達',
          'primary_taxon': 'SERVER_RAIL_HIGH_VISIBILITY',
          'themes': ['伺服器滑軌', '機構件', '水冷/散熱題材', 'AI伺服器']},
 '6806': {'name': '森崴能源', 'primary_taxon': 'GREEN_ENERGY_PROJECT_EPC', 'themes': ['儲能', '綠能工程', '再生能源', '專案認列']},
 '6811': {'name': '宏碁資訊', 'primary_taxon': 'IT_SERVICES_SYSTEM_INTEGRATION', 'themes': ['雲端', '系統整合', '資訊服務']},
 '6909': {'name': '創控', 'primary_taxon': 'FAB_FACILITY_MATERIALS', 'themes': ['AMC監控', '半導體廠務', '精密檢測設備']},
 '6937': {'name': '天虹', 'primary_taxon': 'SEMICAP_ADV_PACKAGING_CORE', 'themes': ['半導體設備', '先進封裝', '設備']},
 '6962': {'name': '奕力-KY', 'primary_taxon': 'DISPLAY_DRIVER_IC_CYCLE', 'themes': ['驅動IC', 'TDDI', '顯示IC']},
 '7749': {'name': '意騰-KY', 'primary_taxon': 'EDGE_AI_SENSOR_SOC', 'themes': ['AI聲學處理', 'Edge AI', 'AI晶片']},
 '7768': {'name': '頌勝科技', 'primary_taxon': 'SEMIMAT_ADVANCED_CONSUMABLES', 'themes': ['CMP研磨墊', '半導體耗材', '先進製程材料']},
 '7769': {'hybrid_taxons': [{'reason': 'AI晶片測試設備受先進封裝/CoWoS擴產帶動，但本業仍為測試設備。',
                             'taxon': 'SEMICAP_ADV_PACKAGING_CORE',
                             'weight': 0.08}],
          'name': '鴻勁',
          'primary_taxon': 'TEST_AUTOMATION_EQUIPMENT',
          'themes': ['測試設備', 'AI晶片測試', '自動化測試']},
 '7822': {'name': '倍利科', 'primary_taxon': 'TEST_AUTOMATION_EQUIPMENT', 'themes': ['半導體檢測', '設備', 'AOI']},
 '8016': {'name': '矽創', 'primary_taxon': 'DISPLAY_DRIVER_IC_CYCLE', 'themes': ['驅動IC', '顯示IC', '消費性IC']},
 '8027': {'name': '鈦昇', 'primary_taxon': 'SEMICAP_GENERAL_EQUIPMENT', 'themes': ['設備', '半導體設備']},
 '8028': {'name': '昇陽半導體', 'primary_taxon': 'WAFER_RECLAIM_THINNING', 'themes': ['晶圓再生', '晶圓薄化', '半導體耗材', '先進封裝周邊']},
 '8033': {'name': '雷虎', 'primary_taxon': 'DEFENSE_DRONE_EVENT', 'themes': ['軍工', '無人機', '事件驅動', '題材']},
 '8039': {'name': '台虹', 'primary_taxon': 'SPECIALTY_CHEM_ELECTRONIC_MATERIALS', 'themes': ['軟板材料', 'FCCL', 'PCB材料', '電子材料']},
 '8046': {'name': '南電', 'primary_taxon': 'ABF_SUBSTRATE', 'themes': ['AI載板', 'HPC', 'ABF', '循環復甦']},
 '8054': {'name': '安國', 'primary_taxon': 'IC_DESIGN_ASIC', 'themes': ['儲存控制', 'AI PC']},
 '8064': {'name': '東捷', 'primary_taxon': 'SEMICAP_GENERAL_EQUIPMENT', 'themes': ['FOPLP', '玻璃基板', '先進封裝設備', 'Micro LED', '自動化設備']},
 '8078': {'name': '華寶', 'primary_taxon': 'LEGACY_TECH_REVIEW', 'themes': ['待確認', '舊資料保留', '低可信度分類']},
 '8081': {'name': '致新', 'primary_taxon': 'POWER_MANAGEMENT_IC_DESIGN', 'themes': ['電源管理IC', '類比IC', '消費性IC']},
 '8103': {'name': '瀚荃', 'primary_taxon': 'CONNECTOR_STANDARD', 'themes': ['連接器', '低軌衛星', '線材']},
 '8110': {'name': '華東', 'primary_taxon': 'MEMORY_OSAT_CYCLE', 'themes': ['記憶體封測', '封測']},
 '8114': {'name': '振樺電', 'primary_taxon': 'IPC_EDGE_AI', 'themes': ['工業電腦', 'POS', 'IPC', 'Edge AI']},
 '8131': {'name': '福懋科', 'primary_taxon': 'MEMORY_OSAT_CYCLE', 'themes': ['記憶體封測', '封測']},
 '8150': {'name': '南茂', 'primary_taxon': 'GENERAL_OSAT_TEST_LEADFRAME', 'themes': ['驅動IC封測', '記憶體封測', '封測', 'PE失真防護']},
 '8210': {'name': '勤誠', 'primary_taxon': 'AI_SERVER_CHASSIS_CORE', 'themes': ['AI機櫃', '伺服器機殼', 'AI伺服器']},
 '8227': {'name': '巨有科技', 'primary_taxon': 'IC_DESIGN_ASIC', 'themes': ['ASIC', '設計服務']},
 '8261': {'name': '富鼎', 'primary_taxon': 'POWER_DISCRETE_COMPONENT_CYCLE', 'themes': ['MOSFET', '功率半導體', '電源管理']},
 '8271': {'name': '宇瞻', 'primary_taxon': 'MEMORY_MODULE_STORAGE_BRAND', 'themes': ['記憶體模組', '工控儲存', '儲存品牌']},
 '8299': {'name': '群聯', 'primary_taxon': 'MEMORY_CONTROLLER_CYCLE', 'themes': ['NAND控制IC', '記憶體', '儲存控制']},
 '8374': {'name': '羅昇', 'primary_taxon': 'INDUSTRIAL_AUTOMATION_CORE', 'themes': ['自動化', '工業自動化']},
 '8996': {'name': '高力', 'primary_taxon': 'THERMAL_LIQUID_CORE', 'themes': ['散熱', '熱交換', '液冷題材']},
 '9958': {'name': '世紀鋼', 'primary_taxon': 'WIND_POWER_INFRA', 'themes': ['風電', '鋼構', '綠能基建']}}
